Travail sur le fichier tests/tokenizeur/scripts/affectation.17.test.php 
tests/tokenizeur/scripts/affectation.17.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable variable 309 "$c"
       "=" 
      gauche : 
          functioncall imagecolorallocate
          appel de fonction : imagecolorallocate: 
              arglist 
              0 : 
                  variable 309 "$image_info"
              1 : 
                  variable 309 "$crouge"
              2 : 
                  variable 309 "$cvert"
              3 : 
                  variable 309 "$cbleu"
