Travail sur le fichier tests/tokenizeur/scripts/affectation.54.test.php 
tests/tokenizeur/scripts/affectation.54.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          cast (292 "(array)")variable $x
              variable $x
       "=" 
      gauche : 
          method variable $a
          appel de methode : functioncall 307 "b" ( arglist(variable $c) ) : 
              functioncall b
              appel de fonction : b: 
                  arglist 
                  0 : 
                      variable $c
