tests/tokenizeur/scripts/affectation.25.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          noscream @
              variable $x
       "=" 
      gauche : 
          cdtternaire ?
          comparaison variable $y 283 "==" sign  "-"literals 1 ? affectation variable $z  "=" literals 2 : variable $a
              comparaison 
              droite : 
                  variable $y
              operateur : 283 "=="
              gauche : 
                  sign  "-"literals 1
                      literals 1
              affectation 
              droite : 
                  variable $z
               "=" 
              gauche : 
                  literals 2
              variable $a
