Working on file 'tests/tokenizeur/scripts/affectation.34.test.php'
tests/tokenizeur/scripts/affectation.34.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          functioncall list
          appel de fonction : list: 
              arglist 
              0 : 
                  variable $x
              1 : 
                  variable $y
       "=" 
      gauche : 
          functioncall explode
          appel de fonction : explode: 
              arglist 
              0 : 
                  literals a
              1 : 
                  literals abacada
