tests/tokenizeur/scripts/affectation.36.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          functioncall list
          function call : list: 
              arglist 
              0 : 
              1 : 
                  variable $x
       "=" 
      right : 
          functioncall explode
          function call : explode: 
              arglist 
              0 : 
                  literals a
              1 : 
                  literals abacada
