Working on file 'tests/tokenizeur/scripts/affectation.41.test.php'
tests/tokenizeur/scripts/affectation.41.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $salt
      273 ".=" 
      gauche : 
          functioncall substr
          appel de fonction : substr: 
              arglist 
              0 : 
                  literals abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789./
              1 : 
                  logique 
                  droite : 
                      functioncall mt_rand
                      appel de fonction : mt_rand: 
                          arglist 
                          Liste d'argument vide
                  operateur :  "&"
                  gauche : 
                      variable $c3
              2 : 
                  literals 1
