tests/tokenizeur/scripts/affectation.43.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparison variable $cause 280 "!==" constante null" )
          block 
          0 : 
              affectation 
              droite : 
                  property variable $xliterals a->
               "=" 
              gauche : 
                  variable $b
          1 : 
              affectation 
              droite : 
                  property variable $xliterals b->
              273 ".=" 
              gauche : 
                  concatenation 
                  0 : 
                      literals  c: 
                  1 : 
                      method variable $d
                      method call : functioncall 307 "e" ( ( ) ) : 
                          functioncall e
                          function call : e: 
                              arglist 
                              Liste d'argument vide
                  2 : 
                      literals f
