tests/tokenizeur/scripts/affectation.16.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $select_increment1
       "=" 
      gauche : 
          functioncall substr
          appel de fonction : substr: 
              arglist 
              0 : 
                  variable $select_increment1
              1 : 
                  literals 1
              2 : 
                  operation 
                  droite : 
                      functioncall strlen
                      appel de fonction : strlen: 
                          arglist 
                          0 : 
                              variable $select_increment1
                  operation :  "-"
                  gauche : 
                      literals 1
