tests/tokenizeur/scripts/affectation.41.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $salt
      273 ".=" 
      right : 
          functioncall substr
          function call : substr: 
              arglist 
              0 : 
                  literals abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789./
              1 : 
                  logique 
                  left : 
                      functioncall mt_rand
                      function call : mt_rand: 
                          arglist 
                          Empty arglist
                  operateur :  "&"
                  right : 
                      variable $c3
              2 : 
                  literals 1
