Travail sur le fichier tests/tokenizeur/scripts/affectation.17.test.php 
tests/tokenizeur/scripts/affectation.17.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable variable $c
       "=" 
      gauche : 
          functioncall imagecolorallocate
          appel de fonction : imagecolorallocate: 
              arglist 
              0 : 
                  variable $image_info
              1 : 
                  variable $crouge
              2 : 
                  variable $cvert
              3 : 
                  variable $cbleu
