Travail sur le fichier tests/tokenizeur/scripts/affectation.40.test.php 
tests/tokenizeur/scripts/affectation.40.test.php
  codephp <?php

  code : 
       class 307 "a"
          block 
          0 : 
              342 "public"function literals __set arglist(variable 309 "$key", variable 309 "$value")
                  block 
                  0 : 
                      affectation 
                      droite : 
                          property property variable 309 "$this"->literals valuevariable 309 "$key"->
                       "=" 
                      gauche : 
                          variable 309 "$value"
