tests/tokenizeur/scripts/affectation.19.test.php
  codephp <?php

  code : 
      functioncall z
      function call : z: 
          arglist 
          0 : 
               argument and initialisation 
                  variable $a
                  literals 1
          1 : 
               argument and initialisation 
                  variable $b
                  literals 2
          2 : 
               argument and initialisation 
                  variable $c
                  literals 3
