Travail sur le fichier tests/tokenizeur/scripts/affectation.16.test.php 
tests/tokenizeur/scripts/affectation.16.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$select_increment1"
       "=" 
      gauche : 
          functioncall substr
          appel de fonction : substr: 
              arglist 
              0 : 
                  variable 309 "$select_increment1"
              1 : 
                  literals 1
              2 : 
                  operation 
                  droite : 
                      functioncall strlen
                      appel de fonction : strlen: 
                          arglist 
                          0 : 
                              variable 309 "$select_increment1"
                  operation :  "-"
                  gauche : 
                      literals 1
