tests/tokenizeur/scripts/affectation.18.test.php
  codephp <?php

  code : 
      function literals a ( )
          block 
          0 : 
              affectation 
              droite : 
                  variable $a
               "=" 
              gauche : 
                  literals 1
          1 : 
              _foreach (variable $b as  => variable $c)
                  block 
                  0 : 
                      affectation 
                      droite : 
                          variable $d
                       "=" 
                      gauche : 
                          literals 2
