tests/tokenizeur/scripts/arrayfct.10.test.php
  codephp <?php

  code : 
      functioncall array
      function call : array: 
          arglist 
          0 : 
              operation 
              droite : 
                  literals x => functioncall 307 "a" ( ( ) ) 
                      literals x
                      functioncall a
                      function call : a: 
                          arglist 
                          Liste d'argument vide
              operation :  "-"
              gauche : 
                  operation 
                  droite : 
                      literals 100
                  operation :  "*"
                  gauche : 
                      functioncall b
                      function call : b: 
                          arglist 
                          0 : 
                              variable $x
