Travail sur le fichier tests/tokenizeur/scripts/array.10.test.php 
tests/tokenizeur/scripts/array.10.test.php
  codephp <?php

  code : 
      functioncall array
      appel de fonction : array: 
          arglist 
          0 : 
              operation 
              droite : 
                  literals 'x' => functioncall 307 "a" ( ( ) ) 
                      literals 'x'
                      functioncall a
                      appel de fonction : a: 
                          arglist 
                          Liste d'argument vide
              operation :  "-"
              gauche : 
                  operation 
                  droite : 
                      literals 100
                  operation :  "*"
                  gauche : 
                      functioncall b
                      appel de fonction : b: 
                          arglist 
                          0 : 
                              variable 309 "$x"
