tests/tokenizeur/scripts/array.11.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          functioncall array
          appel de fonction : array: 
              arglist 
              0 : 
                  literals a
              1 : 
                  literals b
              2 : 
                  literals )
              3 : 
                  literals }
              4 : 
                  literals {
              5 : 
                  literals (
