tests/tokenizeur/scripts/arrayfct.8.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $x
       "=" 
      right : 
          functioncall array
          function call : 360 "array": 
              arglist 
              0 : 
                  literals b => affectation variable $a  "=" constante true
                      literals b
                      affectation 
                      left : 
                          variable $a
                       "=" 
                      right : 
                          constante (                          true )
