Travail sur le fichier tests/tokenizeur/scripts/array.9.test.php 
tests/tokenizeur/scripts/array.9.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $z
       "=" 
      gauche : 
          functioncall array
          appel de fonction : array: 
              arglist 
              0 : 
                  literals 'a' => functioncall variable $c ( arglist(literals 'b') ) 
                      literals 'a'
                      functioncall $c
                      appel de fonction : $c: 
                          arglist 
                          0 : 
                              literals 'b'
