Travail sur le fichier tests/tokenizeur/scripts/array.8.test.php 
tests/tokenizeur/scripts/array.8.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          functioncall array
          appel de fonction : array: 
              arglist 
              0 : 
                  literals b => affectation variable $a  "=" constante true
                      literals b
                      affectation 
                      droite : 
                          variable $a
                       "=" 
                      gauche : 
                          constante (                          true )
