tests/tokenizeur/scripts/array.4.test.php
  codephp <?php

  code : 
      functioncall array
      function call : array: 
          arglist 
          0 : 
              literals 1
          1 : 
              literals 2
          2 : 
              functioncall array
              function call : array: 
                  arglist 
                  0 : 
                      literals 3
                  1 : 
                      literals 4
          3 : 
              literals 5
