tests/tokenizeur/scripts/arrayfct.9.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $z
       "=" 
      right : 
          functioncall array
          function call : array: 
              arglist 
              0 : 
                  literals a => functioncall variable $c ( arglist(literals b) ) 
                      literals a
                      functioncall $c
                      function call : $c: 
                          arglist 
                          0 : 
                              literals b
