Working on file 'tests/tokenizeur/scripts/block.9.test.php'
tests/tokenizeur/scripts/block.9.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "variable $j" )
          block 
          0 : 
              rawtext 
              Texte : "311 "<a>""
          1 : 
              variable $p_field_id
          2 : 
              rawtext 
              Texte : "311 "</a>""
