Travail sur le fichier tests/tokenizeur/scripts/block.6.test.php 
tests/tokenizeur/scripts/block.6.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparaison variable $a 282 "!=" tableau tableau tableau variable $b[literals 'c'][literals 'd'][literals 0]" )
          block 
          0 : 
              affectation 
              droite : 
                  variable $a
               "=" 
              gauche : 
                  tableau
                      tableau
                          tableau
                              variable $b
                              literals 'c'
                          literals 'd'
                      literals 0
