tests/tokenizeur/scripts/block.1.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "functioncall 351 "empty" ( arglist(tableau variable $row[literals 0]) ) " )
          block 
          0 : 
              affectation 
              droite : 
                  tableau
                      variable $date_choisie
                      literals 0
               "=" 
              gauche : 
                  functioncall date
                  function call : date: 
                      arglist 
                      0 : 
                          literals Y
          1 : 
              affectation 
              droite : 
                  tableau
                      variable $date_choisie
                      literals 1
               "=" 
              gauche : 
                  functioncall date
                  function call : date: 
                      arglist 
                      0 : 
                          literals m
          2 : 
              affectation 
              droite : 
                  tableau
                      variable $date_choisie
                      literals 2
               "=" 
              gauche : 
                  functioncall date
                  function call : date: 
                      arglist 
                      0 : 
                          literals j
