Travail sur le fichier tests/tokenizeur/scripts/block.5.test.php 
tests/tokenizeur/scripts/block.5.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          ifthen if
          Condition 0) 
              parentheses 
              ( "logique comparaison variable 309 "$a" 283 "==" tableau variable 309 "$b"[literals 'c'] 278 "||" parentheses (comparaison variable 309 "$d" 283 "==" literals '')" )
              block 
              0 : 
                  functioncall echo
                  appel de fonction : echo: 
                      arglist 
                      0 : 
                          literals 'e'
      1 : 
          functioncall echo
          appel de fonction : echo: 
              arglist 
              0 : 
                  literals 'f'
