Travail sur le fichier tests/tokenizeur/scripts/block.10.test.php 
tests/tokenizeur/scripts/block.10.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "variable 309 "$j"" )
          block 
          0 : 
              rawtext 
              Texte : "311 "
""
          1 : 
              variable 309 "$x"
          2 : 
              rawtext 
              Texte : "311 "
""
