Travail sur le fichier tests/tokenizeur/scripts/cdtternaire.19.test.php 
tests/tokenizeur/scripts/cdtternaire.19.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$a"
       "=" 
      gauche : 
          cdtternaire ?
          functioncall 351 "empty" ( arglist(variable 309 "$b") )  ? affectation variable 309 "$d" 273 ".=" concatenation literals ' ' . variable 309 "$e"   : affectation variable 309 "$d" 273 ".=" concatenation literals ' ' . variable 309 "$e"  
              functioncall empty
              appel de fonction : empty: 
                  arglist 
                  0 : 
                      variable 309 "$b"
              affectation 
              droite : 
                  variable 309 "$d"
              273 ".=" 
              gauche : 
                  concatenation 
                  0 : 
                      literals ' '
                  1 : 
                      variable 309 "$e"
              affectation 
              droite : 
                  variable 309 "$d"
              273 ".=" 
              gauche : 
                  concatenation 
                  0 : 
                      literals ' '
                  1 : 
                      variable 309 "$e"
