Travail sur le fichier tests/tokenizeur/scripts/cdtternaire.5.test.php 
tests/tokenizeur/scripts/cdtternaire.5.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$x"
       "=" 
      gauche : 
          cdtternaire ?
          literals 1 ? literals 2 : tableau variable 309 "$x"[literals 1]
              literals 1
              literals 2
              tableau
                  variable 309 "$x"
                  literals 1
