tests/tokenizeur/scripts/cdtternaire.7.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          cdtternaire ?
          literals 1 ? literals 2 : method variable $x->functioncall 307 "y" ( ( ) ) 
              literals 1
              literals 2
              method variable $x
              method call : functioncall 307 "y" ( ( ) ) : 
                  functioncall y
                  function call : y: 
                      arglist 
                      Liste d'argument vide
