Travail sur le fichier tests/tokenizeur/scripts/cdtternaire.17.test.php 
tests/tokenizeur/scripts/cdtternaire.17.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          ifthen if
          Condition 0) 
              parentheses 
              ( "literals 1" )
              block 
              0 : 
                  affectation 
                  droite : 
                      variable 309 "$x"
                   "=" 
                  gauche : 
                      literals 1
      1 : 
          cdtternaire ?
          parentheses (functioncall 307 "function_exists" ( arglist(literals 'a') ) ) ? functioncall 307 "b" ( arglist(literals "d") )  : literals ""
              parentheses 
              ( "functioncall 307 "function_exists" ( arglist(literals 'a') ) " )
              functioncall b
              appel de fonction : b: 
                  arglist 
                  0 : 
                      literals "d"
              literals ""
