tests/tokenizeur/scripts/cdtternaire.19.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $a
       "=" 
      gauche : 
          cdtternaire ?
          functioncall 351 "empty" ( arglist(variable $b) )  ? affectation variable $d 273 ".=" concatenation literals   . variable $e   : affectation variable $d 273 ".=" concatenation literals   . variable $e  
              functioncall empty
              appel de fonction : empty: 
                  arglist 
                  0 : 
                      variable $b
              affectation 
              droite : 
                  variable $d
              273 ".=" 
              gauche : 
                  concatenation 
                  0 : 
                      literals  
                  1 : 
                      variable $e
              affectation 
              droite : 
                  variable $d
              273 ".=" 
              gauche : 
                  concatenation 
                  0 : 
                      literals  
                  1 : 
                      variable $e
