Travail sur le fichier tests/tokenizeur/scripts/cdtternaire.6.test.php 
tests/tokenizeur/scripts/cdtternaire.6.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$x"
       "=" 
      gauche : 
          cdtternaire ?
          literals 1 ? literals 2 : tableau tableau tableau variable 309 "$x"[literals 1][literals 2][literals 3]
              literals 1
              literals 2
              tableau
                  tableau
                      tableau
                          variable 309 "$x"
                          literals 1
                      literals 2
                  literals 3
