Working on file 'tests/tokenizeur/scripts/cdtternaire.5.test.php'
tests/tokenizeur/scripts/cdtternaire.5.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          cdtternaire ?
          literals 1 ? literals 2 : tableau variable $x[literals 1]
              literals 1
              literals 2
              tableau
                  variable $x
                  literals 1
