Travail sur le fichier tests/tokenizeur/scripts/cdtternaire.16.test.php 
tests/tokenizeur/scripts/cdtternaire.16.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          ifthen if
          Condition 0) 
              parentheses 
              ( "variable 309 "$x"" )
              block 
              0 : 
                  affectation 
                  droite : 
                      variable 309 "$x"
                   "=" 
                  gauche : 
                      literals 1
      1 : 
          cdtternaire ?
          parentheses (functioncall 307 "function_exists" ( arglist(literals 'a') ) ) ? functioncall 307 "a" ( arglist(literals "b") )  : literals ""
              parentheses 
              ( "functioncall 307 "function_exists" ( arglist(literals 'a') ) " )
              functioncall a
              appel de fonction : a: 
                  arglist 
                  0 : 
                      literals "b"
              literals ""
