tests/tokenizeur/scripts/cdtternaire.14.test.php
  codephp <?php 
  code : 
      _foreach (variable $b as  => variable $c)
          block 
          0 : 
              rawtext 
              Texte : "311 "TR ""
          1 : 
              functioncall echo
              appel de fonction : echo: 
                  arglist 
                  0 : 
                      cdtternaire ?
                      functioncall 350 "isset" ( arglist(variable $a) )  ? literals desc : literals asc
                          functioncall isset
                          appel de fonction : isset: 
                              arglist 
                              0 : 
                                  variable $a
                          literals desc
                          literals asc
          2 : 
              rawtext 
              Texte : "311 " TR 
""
