tests/tokenizeur/scripts/cdtternaire.2.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $categorie
       "=" 
      gauche : 
          cdtternaire ?
          parentheses (comparaison variable $categorie_id 282 "!=" literals ) ? concatenation variable $categorie_id . literals  -  . variable $categorie_nom   : literals 
              parentheses 
              ( "comparaison variable $categorie_id 282 "!=" literals " )
              concatenation 
              0 : 
                  variable $categorie_id
              1 : 
                  literals  - 
              2 : 
                  variable $categorie_nom
              literals 
