tests/tokenizeur/scripts/cdtternaire.13.test.php
  codephp <?php 
  code : 
      _for 
        Init : affectation variable $b  "=" literals 0;
        Fin  : comparaison variable $b  "<" literals 1;
        Incr : postplusplus 297 "++"variable $b;
          block 
          0 : 
              rawtext 
              Texte : "311 "TR ""
          1 : 
              functioncall echo
              appel de fonction : echo: 
                  arglist 
                  0 : 
                      cdtternaire ?
                      functioncall 350 "isset" ( arglist(variable $a) )  ? literals desc : literals asc
                          functioncall isset
                          appel de fonction : isset: 
                              arglist 
                              0 : 
                                  variable $a
                          literals desc
                          literals asc
          2 : 
              rawtext 
              Texte : "311 " TR 
""
