Travail sur le fichier tests/tokenizeur/scripts/cdtternaire.3.test.php 
tests/tokenizeur/scripts/cdtternaire.3.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$rech_ven"
       "=" 
      gauche : 
          cdtternaire ?
          functioncall 350 "isset" ( arglist(tableau variable 309 "$_REQUEST"[literals 'rech_ven']) )  ? tableau variable 309 "$_REQUEST"[literals 'rech_ven'] : literals ""
              functioncall isset
              appel de fonction : isset: 
                  arglist 
                  0 : 
                      tableau
                          variable 309 "$_REQUEST"
                          literals 'rech_ven'
              tableau
                  variable 309 "$_REQUEST"
                  literals 'rech_ven'
              literals ""
