tests/tokenizeur/scripts/cdtternaire.11.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          tableau
              variable $a
              cdtternaire ?
              parentheses (variable $b) ? functioncall 307 "strtoupper" ( arglist(property variable $e->literals f) )  : property variable $e->literals f
                  parentheses 
                  ( "variable $b" )
                  functioncall strtoupper
                  appel de fonction : strtoupper: 
                      arglist 
                      0 : 
                          property variable $eliterals f->
                  property variable $eliterals f->
       "=" 
      gauche : 
          variable $f
