Travail sur le fichier tests/tokenizeur/scripts/classe.20.test.php 
tests/tokenizeur/scripts/classe.20.test.php
  codephp <?php 
  code : 
       class 307 "x"
          block 
          0 : 
               343 "protected"347 "static"variable $a, variable $b, variable $c
          1 : 
               343 "protected"347 "static"variable $d, variable $e, variable $f
          2 : 
               342 "public"347 "static"variable $g, variable $h, variable $i
          3 : 
               342 "public"347 "static"variable $j, variable $k, variable $l
          4 : 
               344 "private"347 "static"variable $m, variable $n, variable $o
          5 : 
               344 "private"347 "static"variable $p, variable $r, variable $s
