tests/tokenizeur/scripts/class.19.test.php
  codephp <?php

  code : 
       class 307 "x"
          block 
          0 : 
               343 "protected"variable $x, variable $y, variable $z
          1 : 
               344 "private"variable $a, variable $b, variable $c
          2 : 
               342 "public"variable $d, variable $e, variable $f
          3 : 
               348 "var"variable $g, variable $h, variable $i
          4 : 
              _static 
                  variable $k
          5 : 
              _static 
                  variable $l
          6 : 
              _static 
                  variable $m
