tests/tokenizeur/scripts/class.32.test.php
  codephp <?php

  code : 
       class 307 "b"
          block 
          0 : 
               348 "var"variable $v1 = _constant null, variable $v2 = _constant null
          1 : 
               344 "private"variable $r1 = _constant null, variable $r2 = _constant null
          2 : 
               343 "protected"variable $o1 = _constant null, variable $o2 = _constant null
          3 : 
               342 "public"variable $u1 = _constant null, variable $u2 = _constant null
