Travail sur le fichier tests/tokenizeur/scripts/classe.18.test.php 
tests/tokenizeur/scripts/classe.18.test.php
  codephp <?php 
  code : 
       class 307 "x"
          block 
          0 : 
               343 "protected"347 "static"variable 309 "$a" = literals 1
          1 : 
               343 "protected"347 "static"variable 309 "$b" = literals 1
          2 : 
               342 "public"347 "static"variable 309 "$c" = literals 1
          3 : 
               342 "public"347 "static"variable 309 "$d" = literals 1
          4 : 
               344 "private"347 "static"variable 309 "$e" = literals 1
          5 : 
               344 "private"347 "static"variable 309 "$f" = literals 1
