Travail sur le fichier tests/tokenizeur/scripts/classe.17.test.php 
tests/tokenizeur/scripts/classe.17.test.php
  codephp <?php 
  code : 
       class 307 "x"
          block 
          0 : 
               343 "protected"347 "static"variable 309 "$a"
          1 : 
               343 "protected"347 "static"variable 309 "$b"
          2 : 
               342 "public"347 "static"variable 309 "$c"
          3 : 
               342 "public"347 "static"variable 309 "$d"
          4 : 
               344 "private"347 "static"variable 309 "$e"
          5 : 
               344 "private"347 "static"variable 309 "$f"
