Travail sur le fichier tests/tokenizeur/scripts/classe.31.test.php 
tests/tokenizeur/scripts/classe.31.test.php
  codephp <?php

  code : 
      346 "abstract" class 307 "a"
          block 
          0 : 
              346 "abstract"function  "&" literals b
                  arglist 
                  0 : 
                      variable $d
                  1 : 
                       argument et initialisation 
                          variable $e
                          constante (                          false )
          1 : 
              346 "abstract"function literals d arglist(variable $e, arginit variable $f = functioncall 360 "array" ( ( ) )  )
                  block 
          2 : 
              function literals g ( )
                  block 
