Working on file 'tests/tokenizeur/scripts/classe.21.test.php'
tests/tokenizeur/scripts/classe.21.test.php
  codephp <?php

  code : 
       class 307 "x"
          block 
          0 : 
               343 "protected"variable $input, variable $output = literals 
          1 : 
              function literals x ( )
                  block 
                  0 : 
                      _return 
                      return : "constante true"
