Travail sur le fichier tests/tokenizeur/scripts/classe.11.test.php 
tests/tokenizeur/scripts/classe.11.test.php
  codephp <?php

  code : 
       class 307 "x" extends constante y implements 307 "z"
          block 
          0 : 
               348 "var"variable $a
          1 : 
               348 "var"variable $b
          2 : 
               348 "var"variable $c
          3 : 
               348 "var"variable $d
