Travail sur le fichier tests/tokenizeur/scripts/classe.16.test.php 
tests/tokenizeur/scripts/classe.16.test.php
  codephp <?php 
  code : 
      345 "final" class 307 "x"
          block 
          0 : 
              342 "public"function literals a ( )
                  block 
                  0 : 
                      affectation 
                      droite : 
                          variable $x
                       "=" 
                      gauche : 
                          literals 1
          1 : 
              344 "private"function literals b ( )
                  block 
                  0 : 
                      affectation 
                      droite : 
                          variable $x
                       "=" 
                      gauche : 
                          literals 1
          2 : 
              343 "protected"function literals c ( )
                  block 
                  0 : 
                      affectation 
                      droite : 
                          variable $x
                       "=" 
                      gauche : 
                          literals 1
