tests/tokenizeur/scripts/class.32.test.php
  codephp <?php

  code : 
       class 307 "b"
          block 
          0 : 
               348 "var"variable $v1 = constante null, variable $v2 = constante null
          1 : 
               344 "private"variable $r1 = constante null, variable $r2 = constante null
          2 : 
               343 "protected"variable $o1 = constante null, variable $o2 = constante null
          3 : 
               342 "public"variable $u1 = constante null, variable $u2 = constante null
