Travail sur le fichier tests/tokenizeur/scripts/classe.19.test.php 
tests/tokenizeur/scripts/classe.19.test.php
  codephp <?php

  code : 
       class 307 "x"
          block 
          0 : 
               343 "protected"variable 309 "$x", variable 309 "$y", variable 309 "$z"
          1 : 
               344 "private"variable 309 "$a", variable 309 "$b", variable 309 "$c"
          2 : 
               342 "public"variable 309 "$d", variable 309 "$e", variable 309 "$f"
          3 : 
               348 "var"variable 309 "$g", variable 309 "$h", variable 309 "$i"
          4 : 
               347 "static"variable 309 "$k", variable 309 "$l", variable 309 "$m"
