Working on file 'tests/tokenizeur/scripts/classe.19.test.php'
tests/tokenizeur/scripts/classe.19.test.php
  codephp <?php

  code : 
       class 307 "x"
          block 
          0 : 
               343 "protected"variable $x, variable $y, variable $z
          1 : 
               344 "private"variable $a, variable $b, variable $c
          2 : 
               342 "public"variable $d, variable $e, variable $f
          3 : 
               348 "var"variable $g, variable $h, variable $i
          4 : 
               347 "static"variable $k, variable $l, variable $m
