Travail sur le fichier tests/tokenizeur/scripts/clevaleur.8.test.php 
tests/tokenizeur/scripts/clevaleur.8.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$x"
       "=" 
      gauche : 
          functioncall array
          appel de fonction : array: 
              arglist 
              0 : 
                  literals 'a' => tableau variable 309 "$b"[variable 309 "$c"]
                      literals 'a'
                      tableau
                          variable 309 "$b"
                          variable 309 "$c"
