Travail sur le fichier tests/tokenizeur/scripts/clevaleur.2.test.php 
tests/tokenizeur/scripts/clevaleur.2.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$TABINDEX"
       "=" 
      gauche : 
          functioncall array
          appel de fonction : array: 
              arglist 
              0 : 
                  literals "bouton0" => postplusplus 297 "++"variable 309 "$nbtab"
                      literals "bouton0"
                      variable 309 "$nbtab"297 "++" 
                          variable 309 "$nbtab"
              1 : 
                  literals "bouton1" => postplusplus 297 "++"variable 309 "$nbtab"
                      literals "bouton1"
                      variable 309 "$nbtab"297 "++" 
                          variable 309 "$nbtab"
              2 : 
                  literals "bouton2" => postplusplus 297 "++"variable 309 "$nbtab"
                      literals "bouton2"
                      variable 309 "$nbtab"297 "++" 
                          variable 309 "$nbtab"
