Working on file 'tests/tokenizeur/scripts/clevaleur.4.test.php'
tests/tokenizeur/scripts/clevaleur.4.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $TABINDEX
       "=" 
      gauche : 
          functioncall array
          appel de fonction : array: 
              arglist 
              0 : 
                  literals bouton0 => postplusplus 296 "--"variable $nbtab
                      literals bouton0
                      variable $nbtab296 "--" 
                          variable $nbtab
              1 : 
                  literals bouton1 => postplusplus 296 "--"variable $nbtab
                      literals bouton1
                      variable $nbtab296 "--" 
                          variable $nbtab
              2 : 
                  literals bouton2 => postplusplus 296 "--"variable $nbtab
                      literals bouton2
                      variable $nbtab296 "--" 
                          variable $nbtab
