Travail sur le fichier tests/tokenizeur/scripts/clevaleur.5.test.php 
tests/tokenizeur/scripts/clevaleur.5.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $TABINDEX
       "=" 
      gauche : 
          functioncall array
          appel de fonction : array: 
              arglist 
              0 : 
                  operation 
                  droite : 
                      literals "bouton0" => literals 1
                          literals "bouton0"
                          literals 1
                  operation :  "+"
                  gauche : 
                      literals 2
