Travail sur le fichier tests/tokenizeur/scripts/clevaleur.1.test.php 
tests/tokenizeur/scripts/clevaleur.1.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$conf"
       "=" 
      gauche : 
          functioncall array
          appel de fonction : array: 
              arglist 
              0 : 
                  concatenation 
                  0 : 
                      literals 'root_path' => property tableau variable 309 "$_SESSION"[literals 'init_infos']->literals doc_root
                          literals 'root_path'
                          property tableau variable 309 "$_SESSION"[literals 'init_infos']literals doc_root->
                  1 : 
                      property tableau variable 309 "$_SESSION"[literals 'init_infos']literals stockage->
                  2 : 
                      literals "/images_pdt/"
                  3 : 
                      variable 309 "$pdt_id"
