tests/tokenizeur/scripts/clevaleur.6.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $a
       "=" 
      gauche : 
          method method_static 307 "b"::functioncall 307 "c" ( arglist(literals d) ) 
          method call : functioncall 307 "e" ( arglist(functioncall 360 "array" ( arglist(clevaleur method variable $f->functioncall 307 "g" ( ( ) )  => variable $h) ) ) ) : 
              functioncall e
              function call : e: 
                  arglist 
                  0 : 
                      functioncall array
                      function call : array: 
                          arglist 
                          0 : 
                              method variable $f->functioncall 307 "g" ( ( ) )  => variable $h
                                  method variable $f
                                  method call : functioncall 307 "g" ( ( ) ) : 
                                      functioncall g
                                      function call : g: 
                                          arglist 
                                          Liste d'argument vide
                                  variable $h
