Travail sur le fichier tests/tokenizeur/scripts/clone.13.test.php 
tests/tokenizeur/scripts/clone.13.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$a"
       "=" 
      gauche : 
          cdtternaire ?
          functioncall 350 "isset" ( arglist(tableau property variable 309 "$b"->literals c[literals 'd']) )  ? _clone clone : method method variable 309 "$f"->functioncall 307 "g" ( ( ) ) ->functioncall 307 "h" ( arglist(literals 'i') ) 
              functioncall isset
              appel de fonction : isset: 
                  arglist 
                  0 : 
                      tableau
                          property variable 309 "$b"literals c->
                          literals 'd'
              _clone 
                  tableau
                      property variable 309 "$c"literals d->
                      literals 'e'
              method method variable 309 "$f"->functioncall 307 "g" ( ( ) ) 
              appel de methode : functioncall 307 "h" ( arglist(literals 'i') ) : 
                  functioncall h
                  appel de fonction : h: 
                      arglist 
                      0 : 
                          literals 'i'
