tests/tokenizeur/scripts/clone.13.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $a
       "=" 
      gauche : 
          ternaryop ?
          functioncall 350 "isset" ( arglist(tableau property variable $b->literals c[literals d]) )  ? _clone clone : method method variable $f->functioncall 307 "g" ( ( ) ) ->functioncall 307 "h" ( arglist(literals i) ) 
              functioncall isset
              function call : isset: 
                  arglist 
                  0 : 
                      tableau
                          property variable $bliterals c->
                          literals d
              _clone 
                  tableau
                      property variable $cliterals d->
                      literals e
              method method variable $f->functioncall 307 "g" ( ( ) ) 
              method call : functioncall 307 "h" ( arglist(literals i) ) : 
                  functioncall h
                  function call : h: 
                      arglist 
                      0 : 
                          literals i
