Travail sur le fichier tests/tokenizeur/scripts/codephp.5.test.php 
tests/tokenizeur/scripts/codephp.5.test.php
  codephp <?php 
  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $x
           "=" 
          gauche : 
              literals 1
      1 : 
          rawtext 
          Texte : "311 "  Espace vide  ""
      2 : 
          affectation 
          droite : 
              variable $x
           "=" 
          gauche : 
              literals 1
