Working on file 'tests/tokenizeur/scripts/codephp.10.test.php'
tests/tokenizeur/scripts/codephp.10.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          logique 
          droite : 
              variable $x
          operateur :  "|"
          gauche : 
              variable $y
      1 : 
          affectation 
          droite : 
              variable $x
           "=" 
          gauche : 
              literals 1
