Travail sur le fichier tests/tokenizeur/scripts/codephp.13.test.php 
tests/tokenizeur/scripts/codephp.13.test.php
  codephp <?php 
  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $x
           "=" 
          gauche : 
              literals 1
      1 : 
          rawtext 
          Texte : "311 "raw
""
      2 : 
          functioncall echo
          appel de fonction : echo: 
              arglist 
              0 : 
                  variable $x
      3 : 
          variable $y
