tests/tokenizeur/scripts/codephp.20.test.php
  rawtext 
  Texte : "311 "<?xml ?>
XML
""
  codephp <?php 
  code : 
      sequence 
      0 : 
          affectation 
          left : 
              variable $x
           "=" 
          right : 
              literals 1
      1 : 
          rawtext 
          Texte : "311 """
      2 : 
          affectation 
          left : 
              variable $y
           "=" 
          right : 
              literals 1
