tests/tokenizeur/scripts/codephp.19.test.php
  codephp <?php 
  code : 
      functioncall echo
      appel de fonction : echo: 
          arglist 
          0 : 
              method_static 
              307 "classe"::functioncall 307 "lang" ( ( ) ) : 
                  functioncall lang
                  appel de fonction : lang: 
                      arglist 
                      Liste d'argument vide
