Travail sur le fichier tests/tokenizeur/scripts/codephp.12.test.php 
tests/tokenizeur/scripts/codephp.12.test.php
  codephp <?php 
  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable 309 "$x"
           "=" 
          gauche : 
              literals 1
      1 : 
          rawtext 
          Texte : "311 """
      2 : 
          functioncall echo
          appel de fonction : echo: 
              variable 309 "$x"
      3 : 
          variable 309 "$y"
