Travail sur le fichier tests/tokenizeur/scripts/codephp.13.test.php 
tests/tokenizeur/scripts/codephp.13.test.php
Plus d'upgrade au cycle 6 
  Token <?php  ( Affichage par défaut)
  block 
  0 : 
      affectation 
      droite : 
          variable 309 "$x"
       "=" 
      gauche : 
          literals 1
  rawtext 
  Texte : "311 "raw
""
  Token = ( Affichage par défaut)
  variable 309 "$x"
  Token ; ( Affichage par défaut)
  variable 309 "$y"
  Token ; ( Affichage par défaut)
  Token ?> ( Affichage par défaut)
