tests/tokenizeur/scripts/codephp.20.test.php
  rawtext 
  Texte : "311 "<?xml ?>
XML
""
  codephp <?php 
  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $x
           "=" 
          gauche : 
              literals 1
      1 : 
          rawtext 
          Texte : "311 """
      2 : 
          affectation 
          droite : 
              variable $y
           "=" 
          gauche : 
              literals 1
