Travail sur le fichier tests/tokenizeur/scripts/comparaison.15.test.php 
tests/tokenizeur/scripts/comparaison.15.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          comparaison 
          droite : 
               new 307 "a" arglist(variable $b) 
          operateur : 288 "instanceof"
          gauche : 
              constante (              d )
