tests/tokenizeur/scripts/comparaison.12.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparaison preplusplus variable $x297 "++" 283 "==" literals 0" )
          block 
          0 : 
              affectation 
              droite : 
                  variable $x
               "=" 
              gauche : 
                  literals 1
