Working on file 'tests/tokenizeur/scripts/comparaison.5.test.php'
tests/tokenizeur/scripts/comparaison.5.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparaison method variable $this->functioncall 307 "methode" ( ( ) )  283 "==" constante false" )
          block 
          0 : 
              _return 
              return : "constante false"
