tests/tokenizeur/scripts/comparison.18.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparison variable $a 283 "==" constante_static 380 "\"\307 "b"::constante c" )
          block 
          0 : 
              _return 
              return : "variable $d"
       else 
          block 
          0 : 
              _return 
              return : "literals f"
