tests/tokenizeur/scripts/comparaison.13.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparaison literals 0 283 "==" postplusplus 297 "++"variable $x" )
          block 
          0 : 
              affectation 
              droite : 
                  variable $x
               "=" 
              gauche : 
                  literals 1
