Travail sur le fichier tests/tokenizeur/scripts/comparaison.13.test.php 
tests/tokenizeur/scripts/comparaison.13.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparaison literals 0 283 "==" postplusplus 297 "++"variable 309 "$x"" )
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$x"
               "=" 
              gauche : 
                  literals 1
