tests/tokenizeur/scripts/comparaison.10.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          ifthen if
          Condition 0) 
              parentheses 
              ( "comparaison functioncall variable $strlen ( arglist(variable $text) )   ">" variable $length" )
              block 
              0 : 
                  affectation 
                  droite : 
                      variable $x
                   "=" 
                  gauche : 
                      literals 1
      1 : 
          ifthen if
          Condition 0) 
              parentheses 
              ( "comparaison parentheses (variable $text)  ">" variable $length" )
              block 
              0 : 
                  affectation 
                  droite : 
                      variable $x
                   "=" 
                  gauche : 
                      literals 1
