tests/tokenizeur/scripts/comparison.16.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparison logique comparison variable $x 283 "==" literals 2 263 "OR" constante PHPVERSION 282 "!=" literals s" )
          block 
          0 : 
              affectation 
              droite : 
                  variable $x
               "=" 
              gauche : 
                  literals 1
