Travail sur le fichier tests/tokenizeur/scripts/comparaison.11.test.php 
tests/tokenizeur/scripts/comparaison.11.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparaison preplusplus variable 309 "$x"296 "--" 283 "==" literals 0" )
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$x"
               "=" 
              gauche : 
                  literals 1
