Working on file 'tests/tokenizeur/scripts/comparaison.9.test.php'
tests/tokenizeur/scripts/comparaison.9.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparaison constante false 281 "===" affectation variable $greeting  "=" functioncall 307 "coucou" ( arglist(literals 1) ) " )
          block 
          0 : 
              affectation 
              droite : 
                  variable $x
               "=" 
              gauche : 
                  literals 1
