Working on file 'tests/tokenizeur/scripts/concatenation.24.test.php'
tests/tokenizeur/scripts/concatenation.24.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          concatenation 
          0 : 
              tableau
                  property variable $thisliterals properties->
                  literals prefix
          1 : 
              property variable $nodeliterals id->
