Travail sur le fichier tests/tokenizeur/scripts/concatenation.16.test.php 
tests/tokenizeur/scripts/concatenation.16.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          concatenation 
          0 : 
              literals A 
          1 : 
              variable method variable $a->functioncall 307 "b" ( arglist(literals c) ) 
          2 : 
              literals  B

