Travail sur le fichier tests/tokenizeur/scripts/concatenation.25.test.php 
tests/tokenizeur/scripts/concatenation.25.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          concatenation 
          0 : 
              literals &nbsp;(
          1 : 
              noscream @
                  297 "++"tableau variable $n[variable $boucle] 
                      tableau
                          variable $n
                          variable $boucle
          2 : 
              literals )
