Travail sur le fichier tests/tokenizeur/scripts/concatenation.27.test.php 
tests/tokenizeur/scripts/concatenation.27.test.php
  codephp <?php

  code : 
      functioncall echo
      appel de fonction : echo: 
          arglist 
          0 : 
              concatenation 
              0 : 
                  literals a
              1 : 
                  tableau
                      tableau
                          variable 309 "$GLOBALS"
                          literals 'b'
                      literals 'c'
              2 : 
                  literals c 
              3 : 
                  variable 309 "$bgcolor"
              4 : 
                  literals  d
