tests/tokenizeur/scripts/concatenation.13.test.php
  codephp <?php

  code : 
      functioncall echo
      function call : echo: 
          arglist 
          0 : 
              concatenation 
              0 : 
                  method variable $a
                  method call : functioncall 307 "b" ( arglist(_array variable $c[constante d]) ) : 
                      functioncall b
                      function call : b: 
                          arglist 
                          0 : 
                              _array
                                  variable $c
                                  constante (                                  d )
              1 : 
                  literals e
              2 : 
                  _array
                      variable $f
                      literals g
              3 : 
                  literals h
