tests/tokenizeur/scripts/concatenation.26.test.php
  codephp <?php

  code : 
      functioncall echo
      appel de fonction : echo: 
          arglist 
          0 : 
              concatenation 
              0 : 
                  literals a
              1 : 
                  tableau
                      variable $GLOBALS
                      literals b
              2 : 
                  literals c 
              3 : 
                  variable $bgcolor
              4 : 
                  literals  d
