Travail sur le fichier tests/tokenizeur/scripts/concatenation.19.test.php 
tests/tokenizeur/scripts/concatenation.19.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$x"
       "=" 
      gauche : 
          concatenation 
          0 : 
              tableau
                  variable 309 "$i"
                  literals 'a'
          1 : 
              literals .
          2 : 
              tableau
                  variable 309 "$i"
                  literals 'b'
          3 : 
              literals .
          4 : 
              tableau
                  variable 309 "$i"
                  literals 'c'
          5 : 
              literals .
          6 : 
              tableau
                  variable 309 "$i"
                  literals 'd'
          7 : 
              literals -
          8 : 
              tableau
                  variable 309 "$i"
                  literals 'e'
          9 : 
              tableau
                  variable 309 "$i"
                  literals 'f'
          10 : 
              literals .
          11 : 
              tableau
                  tableau
                      tableau
                          variable 309 "$i"
                          literals 'g'
                      literals 'x'
                  literals 'x'
