Working on file 'tests/tokenizeur/scripts/concatenation.12.test.php'
tests/tokenizeur/scripts/concatenation.12.test.php
  codephp <?php

  code : 
      functioncall echo
      appel de fonction : echo: 
          arglist 
          0 : 
              concatenation 
              0 : 
                  method_static 
                  307 "a"::functioncall 307 "b" ( arglist(tableau variable $c[constante d]) ) : 
                      functioncall b
                      appel de fonction : b: 
                          arglist 
                          0 : 
                              tableau
                                  variable $c
                                  constante (                                  d )
              1 : 
                  literals e
              2 : 
                  tableau
                      variable $f
                      literals g
              3 : 
                  literals h
