Travail sur le fichier tests/tokenizeur/scripts/concatenation.24.test.php 
tests/tokenizeur/scripts/concatenation.24.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$x"
       "=" 
      gauche : 
          concatenation 
          0 : 
              tableau
                  property variable 309 "$this"literals properties->
                  literals 'prefix'
          1 : 
              property variable 309 "$node"literals id->
