Travail sur le fichier tests/tokenizeur/scripts/concatenation.13.test.php 
tests/tokenizeur/scripts/concatenation.13.test.php
  codephp <?php

  code : 
      functioncall echo
      appel de fonction : echo: 
          arglist 
          0 : 
              concatenation 
              0 : 
                  method variable 309 "$a"
                  appel de methode : functioncall 307 "b" ( arglist(tableau variable 309 "$c"[constante d]) ) : 
                      functioncall b
                      appel de fonction : b: 
                          arglist 
                          0 : 
                              tableau
                                  variable 309 "$c"
                                  constante (                                  d )
              1 : 
                  literals 'e'
              2 : 
                  tableau
                      variable 309 "$f"
                      literals 'g'
              3 : 
                  literals 'h'
