tests/tokenizeur/scripts/concatenation.27.test.php
  codephp <?php

  code : 
      functioncall echo
      function call : echo: 
          arglist 
          0 : 
              concatenation 
              0 : 
                  literals a
              1 : 
                  tableau
                      tableau
                          variable $GLOBALS
                          literals b
                      literals c
              2 : 
                  literals c 
              3 : 
                  variable $bgcolor
              4 : 
                  literals  d
