Travail sur le fichier tests/tokenizeur/scripts/concatenation.18.test.php 
tests/tokenizeur/scripts/concatenation.18.test.php
  codephp <?php

  code : 
      functioncall echo
      appel de fonction : echo: 
          arglist 
          0 : 
              concatenation 
              0 : 
                  literals a 
              1 : 
                  variable property variable 309 "$this"->literals b
              2 : 
                  literals  c 
              3 : 
                  property variable 309 "$item"literals d->
              4 : 
                  literals  
              5 : 
                  variable 309 "$e"
              6 : 
                  literals  f 
