Working on file 'tests/tokenizeur/scripts/constante_classe.4.test.php'
tests/tokenizeur/scripts/constante_classe.4.test.php
  codephp <?php

  code : 
       class 307 "MyMin"
          block 
          0 : 
              constante_classe               constante a = literals 1 
          1 : 
              constante_classe               constante b = literals 2 
          2 : 
              constante_classe               constante c = literals 3 
          3 : 
              constante_classe               constante d = literals 4.2 
