tests/tokenizeur/scripts/constante_classe.5.test.php
  codephp <?php

  code : 
       class 307 "MyMin"
          block 
          0 : 
              constante_classe               constante a = literals 1 
          1 : 
              constante_classe               constante b = literals 2 
          2 : 
              constante_classe               constante c = literals 3 
          3 : 
              constante_classe               constante ac = literals 1 
          4 : 
              constante_classe               constante bc = literals 2 
          5 : 
              constante_classe               constante cc = literals 3 
          6 : 
              constante_classe               constante ad = literals 1 
