Travail sur le fichier tests/tokenizeur/scripts/decalage.9.test.php 
tests/tokenizeur/scripts/decalage.9.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$a"
      273 ".=" 
      gauche : 
          functioncall pack
          appel de fonction : pack: 
              arglist 
              0 : 
                  decalage 
                  droite : 
                      literals 36
                  operation : 286 ">>"
                  gauche : 
                      variable 309 "$c"
              1 : 
                  decalage 
                  droite : 
                      literals 24
                  operation : 286 ">>"
                  gauche : 
                      variable 309 "$c"
              2 : 
                  decalage 
                  droite : 
                      literals 16
                  operation : 286 ">>"
                  gauche : 
                      variable 309 "$d"
              3 : 
                  decalage 
                  droite : 
                      literals 8
                  operation : 286 ">>"
                  gauche : 
                      variable 309 "$e"
              4 : 
                  decalage 
                  droite : 
                      literals 8
                  operation : 286 ">>"
                  gauche : 
                      variable 309 "$c"
