tests/tokenizeur/scripts/decalage.9.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $a
      273 ".=" 
      right : 
          functioncall pack
          function call : pack: 
              arglist 
              0 : 
                  decalage 
                  left : 
                      variable $c
                  operation : 286 ">>"
                  right : 
                      literals 36
              1 : 
                  decalage 
                  left : 
                      variable $c
                  operation : 286 ">>"
                  right : 
                      literals 24
              2 : 
                  decalage 
                  left : 
                      variable $d
                  operation : 286 ">>"
                  right : 
                      literals 16
              3 : 
                  decalage 
                  left : 
                      variable $e
                  operation : 286 ">>"
                  right : 
                      literals 8
              4 : 
                  decalage 
                  left : 
                      variable $c
                  operation : 286 ">>"
                  right : 
                      literals 8
