Travail sur le fichier tests/tokenizeur/scripts/dowhile.2.test.php 
tests/tokenizeur/scripts/dowhile.2.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          _dowhile 
              block 
              0 : 
                  affectation 
                  droite : 
                      variable 309 "$x"
                   "=" 
                  gauche : 
                      literals 1
              parentheses 
              ( "comparaison property variable 309 "$this"->literals _code  "<" literals 200" )
      1 : 
          affectation 
          droite : 
              property variable 309 "$this"literals _ready->
           "=" 
          gauche : 
              constante (              true )
