tests/tokenizeur/scripts/dowhile.2.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          _dowhile 
              block 
              0 : 
                  affectation 
                  droite : 
                      variable $x
                   "=" 
                  gauche : 
                      literals 1
              parentheses 
              ( "comparison property variable $this->literals _code  "<" literals 200" )
      1 : 
          affectation 
          droite : 
              property variable $thisliterals _ready->
           "=" 
          gauche : 
              constante (              true )
