Travail sur le fichier tests/tokenizeur/scripts/for.5.test.php 
tests/tokenizeur/scripts/for.5.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable 309 "$i"  "=" literals 0;
        Fin  : comparaison variable 309 "$i"  "<" literals 5;
        Incr : ;
          affectation 
          droite : 
              variable 309 "$x"
           "=" 
          gauche : 
              literals 's'
