tests/tokenizeur/scripts/for.19.test.php
  codephp <?php

  code : 
      _for 
        Init : block {affectation variable $a  "=" literals 0
arginit variable $b = literals 1 
arginit variable $c = functioncall 360 "array" ( arglist(literals 1, literals 2, literals 3, literals 4, literals 5) )  
arginit variable $d = constante false 
affectation variable $e  "=" literals  };
        Fin  : comparison variable $i  "<" literals 5;
        Incr : postplusplus 297 "++"variable $i;
          block 
          0 : 
              affectation 
              droite : 
                  variable $x
               "=" 
              gauche : 
                  literals 1
