Travail sur le fichier tests/tokenizeur/scripts/for.34.test.php 
tests/tokenizeur/scripts/for.34.test.php
  codephp <?php

  code : 
      _for 
        Init : ;
        Fin  : block {comparaison variable 309 "$a"  "<" literals 1
postplusplus 297 "++"variable 309 "$c" };
        Incr : affectation variable 309 "$b" 277 "+=" literals 2;
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$d"
               "=" 
              gauche : 
                  literals 1
