Travail sur le fichier tests/tokenizeur/scripts/for.20.test.php 
tests/tokenizeur/scripts/for.20.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable 309 "$a"  "=" literals 0;
        Fin  : block {comparaison variable 309 "$i"  "<" literals 5
arginit variable 309 "$b" = literals 1 
arginit variable 309 "$c" = functioncall 360 "array" ( arglist(literals 1, literals 2, literals 3, literals 4, literals 5) )  
arginit variable 309 "$d" = constante false 
affectation variable 309 "$e"  "=" literals "" };
        Incr : postplusplus 297 "++"variable 309 "$i";
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$x"
               "=" 
              gauche : 
                  literals 1
