Travail sur le fichier tests/tokenizeur/scripts/for.35.test.php 
tests/tokenizeur/scripts/for.35.test.php
  codephp <?php

  code : 
      _for 
        Init : block {affectation variable 309 "$i"  "=" literals 1
affectation variable 309 "$nb"  "=" tableau variable 309 "$a"[literals 'b'] };
        Fin  : variable 309 "$c";
        Incr : preplusplus variable 309 "$d"296 "--";
          affectation 
          droite : 
              tableau variable 309 "$e"[literals 'x'][]
                  tableau
                      variable 309 "$e"
                      literals 'x'
           "=" 
          gauche : 
              variable 309 "$i"297 "++" 
                  variable 309 "$i"
