Travail sur le fichier tests/tokenizeur/scripts/for.8.test.php 
tests/tokenizeur/scripts/for.8.test.php
  codephp <?php

  code : 
      _for 
        Init : ;
        Fin  : comparaison variable 309 "$i"  "<" literals 5;
        Incr : postplusplus 297 "++"variable 309 "$i";
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$x"
               "=" 
              gauche : 
                  literals 's'
