Travail sur le fichier tests/tokenizeur/scripts/for.9.test.php 
tests/tokenizeur/scripts/for.9.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable 309 "$u"  "=" affectation variable 309 "$v"  "=" affectation variable 309 "$w"  "=" affectation variable 309 "$x"  "=" affectation variable 309 "$y"  "=" affectation variable 309 "$z"  "=" affectation variable 309 "$a"  "=" literals 0;
        Fin  : comparaison variable 309 "$b"  "<" variable 309 "$c";
        Incr : postplusplus 297 "++"variable 309 "$d";
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$x"
               "=" 
              gauche : 
                  literals 1
