Travail sur le fichier tests/tokenizeur/scripts/for.11.test.php 
tests/tokenizeur/scripts/for.11.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable 309 "$u"  "=" literals 0;
        Fin  : comparaison variable 309 "$v"  "<" variable 309 "$w";
        Incr : affectation variable 309 "$e"  "=" affectation variable 309 "$x"  "=" affectation variable 309 "$y"  "=" affectation variable 309 "$z"  "=" affectation variable 309 "$a"  "=" affectation variable 309 "$b"  "=" affectation variable 309 "$c"  "=" operation variable 309 "$d"  "+" literals 1;
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$x"
               "=" 
              gauche : 
                  literals 1
