Travail sur le fichier tests/tokenizeur/scripts/for.12.test.php 
tests/tokenizeur/scripts/for.12.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable $a  "=" literals 1;
        Fin  : comparaison variable $a  "<" operation variable $b  "+" literals 1;
        Incr : postplusplus 297 "++"variable $a;
          block 
          0 : 
              affectation 
              droite : 
                  variable $c
               "=" 
              gauche : 
                  literals 0
