Travail sur le fichier tests/tokenizeur/scripts/for.18.test.php 
tests/tokenizeur/scripts/for.18.test.php
  codephp <?php

  code : 
      _for 
        Init : block {affectation variable $i  "=" literals 0
affectation variable $a  "=" literals 1 };
        Fin  : block {comparaison variable $i  "<" literals 0
affectation variable $b  "=" literals 2 };
        Incr : postplusplus 297 "++"variable $i;
          functioncall unset
          appel de fonction : unset: 
              arglist 
              0 : 
                  variable $t
