Working on file 'tests/tokenizeur/scripts/for.23.test.php'
tests/tokenizeur/scripts/for.23.test.php
  codephp <?php 
  code : 
      _for 
        Init : affectation variable $i  "=" literals 0;
        Fin  : comparaison variable $i  "<" literals 1;
        Incr : postplusplus 297 "++"variable $i;
          affectation 
          droite : 
              variable $a[]
                  variable $a
           "=" 
          gauche : 
              method variable $b
              appel de methode : functioncall 307 "c" ( arglist(variable $d) ) : 
                  functioncall c
                  appel de fonction : c: 
                      arglist 
                      0 : 
                          variable $d
