Working on file 'tests/tokenizeur/scripts/for.13.test.php'
tests/tokenizeur/scripts/for.13.test.php
  codephp <?php

  code : 
      _for 
        Init : block {affectation variable $i  "=" literals 0
affectation variable $a  "=" literals 1 };
        Fin  : comparaison variable $i  "<" literals 0;
        Incr : postplusplus 297 "++"variable $i;
          block 
          0 : 
              affectation 
              droite : 
                  variable $w
               "=" 
              gauche : 
                  literals 1
