Travail sur le fichier tests/tokenizeur/scripts/for.4.test.php 
tests/tokenizeur/scripts/for.4.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable 309 "$i"  "=" literals 0;
        Fin  : ;
        Incr : postplusplus 297 "++"variable 309 "$i";
          affectation 
          droite : 
              variable 309 "$x"
           "=" 
          gauche : 
              literals 's'
