tests/tokenizeur/scripts/for.20.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable $a  "=" literals 0;
        Fin  : block {comparison variable $i  "<" literals 5
arginit variable $b = literals 1 
arginit variable $c = functioncall 360 "array" ( arglist(literals 1, literals 2, literals 3, literals 4, literals 5) )  
arginit variable $d = constante false 
affectation variable $e  "=" literals  };
        Incr : postplusplus 297 "++"variable $i;
          block 
          0 : 
              affectation 
              left : 
                  variable $x
               "=" 
              right : 
                  literals 1
