Travail sur le fichier tests/tokenizeur/scripts/for.22.test.php 
tests/tokenizeur/scripts/for.22.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable 309 "$i"  "=" literals 1;
        Fin  : comparaison variable 309 "$i"  "<" literals 2;
        Incr : postplusplus 297 "++"variable 309 "$i";
          method variable 309 "$this"
          appel de methode : functioncall 307 "d" ( arglist(literals 'e') ) : 
              functioncall d
              appel de fonction : d: 
                  arglist 
                  0 : 
                      literals 'e'
