tests/tokenizeur/scripts/for.16.test.php
  codephp <?php

  code : 
      _for 
        Init : block {affectation variable $i  "=" literals 0
affectation variable $a  "=" literals 1 };
        Fin  : comparison variable $i  "<" literals 0;
        Incr : block {postplusplus 297 "++"variable $i
arginit variable $c = literals 3  };
          block 
          0 : 
              affectation 
              droite : 
                  variable $w
               "=" 
              gauche : 
                  literals 1
