Travail sur le fichier tests/tokenizeur/scripts/for.14.test.php 
tests/tokenizeur/scripts/for.14.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable $i  "=" literals 0;
        Fin  : block {comparaison variable $i  "<" literals 0
affectation variable $a  "=" literals 1 };
        Incr : postplusplus 297 "++"variable $i;
          block 
          0 : 
              affectation 
              droite : 
                  variable $w
               "=" 
              gauche : 
                  literals 1
