tests/tokenizeur/scripts/for.34.test.php
  codephp <?php

  code : 
      _for 
        Init : ;
        Fin  : block {comparaison variable $a  "<" literals 1
postplusplus 297 "++"variable $c };
        Incr : affectation variable $b 277 "+=" literals 2;
          block 
          0 : 
              affectation 
              droite : 
                  variable $d
               "=" 
              gauche : 
                  literals 1
