Travail sur le fichier tests/tokenizeur/scripts/for.33.test.php 
tests/tokenizeur/scripts/for.33.test.php
  codephp <?php

  code : 
      _for 
        Init : ;
        Fin  : comparaison variable 309 "$a"  "<" literals 1;
        Incr : block {affectation variable 309 "$b" 277 "+=" literals 2
postplusplus 297 "++"variable 309 "$c" };
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$d"
               "=" 
              gauche : 
                  literals 1
