Travail sur le fichier tests/tokenizeur/scripts/for.15.test.php 
tests/tokenizeur/scripts/for.15.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable $i  "=" literals 0;
        Fin  : comparaison variable $i  "<" literals 0;
        Incr : block {postplusplus 297 "++"variable $i
arginit variable $a = literals 1  };
          block 
          0 : 
              affectation 
              droite : 
                  variable $w
               "=" 
              gauche : 
                  literals 1
