tests/tokenizeur/scripts/for.36.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable $i  "=" literals 0;
        Fin  : comparaison variable $i  "<" functioncall 307 "count" ( arglist(variable $regex) ) ;
        Incr : preplusplus variable $i297 "++";
          affectation 
          droite : 
              property variable $thisliterals a->
           "=" 
          gauche : 
              functioncall preg_replace_callback
              function call : preg_replace_callback: 
                  arglist 
                  0 : 
                      tableau
                          variable $regex
                          variable $i
                  1 : 
                      tableau
                          variable $replace
                          variable $i
                  2 : 
                      property variable $thisliterals b->
