Travail sur le fichier tests/tokenizeur/scripts/for.8.test.php 
tests/tokenizeur/scripts/for.8.test.php
  codephp <?php

  code : 
      _for 
        Init : ;
        Fin  : comparaison variable $i  "<" literals 5;
        Incr : postplusplus 297 "++"variable $i;
          block 
          0 : 
              affectation 
              droite : 
                  variable $x
               "=" 
              gauche : 
                  literals s
