Travail sur le fichier tests/tokenizeur/scripts/for.12.test.php 
tests/tokenizeur/scripts/for.12.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable 309 "$a"  "=" literals 1;
        Fin  : comparaison variable 309 "$a"  "<" operation variable 309 "$b"  "+" literals 1;
        Incr : postplusplus 297 "++"variable 309 "$a";
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$c"
               "=" 
              gauche : 
                  literals 0
