Travail sur le fichier tests/tokenizeur/scripts/for.10.test.php 
tests/tokenizeur/scripts/for.10.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable $u  "=" literals 0;
        Fin  : affectation variable $v  "=" affectation variable $w  "=" affectation variable $x  "=" affectation variable $y  "=" affectation variable $z  "=" affectation variable $a  "=" comparaison variable $b  "<" variable $c;
        Incr : postplusplus 297 "++"variable $d;
          block 
          0 : 
              affectation 
              droite : 
                  variable $x
               "=" 
              gauche : 
                  literals 1
