Travail sur le fichier tests/tokenizeur/scripts/for.3.test.php 
tests/tokenizeur/scripts/for.3.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable $i  "=" literals 0;
        Fin  : comparaison variable $i  "<" literals 2;
        Incr : postplusplus 297 "++"variable $i;
          affectation 
          droite : 
              variable $x
           "=" 
          gauche : 
              literals s
