Travail sur le fichier tests/tokenizeur/scripts/for.22.test.php 
tests/tokenizeur/scripts/for.22.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable $i  "=" literals 1;
        Fin  : comparaison variable $i  "<" literals 2;
        Incr : postplusplus 297 "++"variable $i;
          method variable $this
          appel de methode : functioncall 307 "d" ( arglist(literals e) ) : 
              functioncall d
              appel de fonction : d: 
                  arglist 
                  0 : 
                      literals e
