Travail sur le fichier tests/tokenizeur/scripts/for.33.test.php 
tests/tokenizeur/scripts/for.33.test.php
  codephp <?php

  code : 
      _for 
        Init : ;
        Fin  : comparaison variable $a  "<" literals 1;
        Incr : block {affectation variable $b 277 "+=" literals 2
postplusplus 297 "++"variable $c };
          block 
          0 : 
              affectation 
              droite : 
                  variable $d
               "=" 
              gauche : 
                  literals 1
