Travail sur le fichier tests/tokenizeur/scripts/for.13.test.php 
tests/tokenizeur/scripts/for.13.test.php
  codephp <?php

  code : 
      _for 
        Init : block {affectation variable 309 "$i"  "=" literals 0
affectation variable 309 "$a"  "=" literals 1 };
        Fin  : comparaison variable 309 "$i"  "<" literals 0;
        Incr : postplusplus 297 "++"variable 309 "$i";
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$w"
               "=" 
              gauche : 
                  literals 1
