Travail sur le fichier tests/tokenizeur/scripts/for.21.test.php 
tests/tokenizeur/scripts/for.21.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable 309 "$a"  "=" literals 0;
        Fin  : comparaison variable 309 "$i"  "<" literals 5;
        Incr : block {postplusplus 297 "++"variable 309 "$i"
arginit variable 309 "$b" = literals 1 
arginit variable 309 "$c" = functioncall 360 "array" ( arglist(literals 1, literals 2, literals 3, literals 4, literals 5) )  
arginit variable 309 "$d" = constante false 
arginit variable 309 "$e" = literals ""  };
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$x"
               "=" 
              gauche : 
                  literals 1
