Travail sur le fichier tests/tokenizeur/scripts/for.16.test.php 
tests/tokenizeur/scripts/for.16.test.php
  codephp <?php

  code : 
      _for 
        Init : block {affectation variable 309 "$i"  "=" literals 0
affectation variable 309 "$a"  "=" literals 1 };
        Fin  : comparaison variable 309 "$i"  "<" literals 0;
        Incr : block {postplusplus 297 "++"variable 309 "$i"
arginit variable 309 "$c" = literals 3  };
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$w"
               "=" 
              gauche : 
                  literals 1
