Travail sur le fichier tests/tokenizeur/scripts/for.24.test.php 
tests/tokenizeur/scripts/for.24.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable $j  "=" literals 0;
        Fin  : comparaison variable $j  "<" variable $n;
        Incr : postplusplus 297 "++"variable $j;
          affectation 
          droite : 
              tableau
                  tableau
                      tableau
                          property variable $aliterals b->
                          tableau
                              tableau
                                  tableau
                                      property variable $cliterals d->
                                      variable $i
                                  literals f
                              literals g
                      literals h
                  tableau
                      tableau
                          tableau
                              tableau
                                  property variable $iliterals j->
                                  variable $i
                              literals k
                          variable $j
                      literals l
           "=" 
          gauche : 
              tableau
                  tableau
                      tableau
                          property variable $pliterals o->
                          variable $i
                      literals p
                  variable $j
