Working on file 'tests/tokenizeur/scripts/for.21.test.php'
tests/tokenizeur/scripts/for.21.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable $a  "=" literals 0;
        Fin  : comparaison variable $i  "<" literals 5;
        Incr : block {postplusplus 297 "++"variable $i
arginit variable $b = literals 1 
arginit variable $c = functioncall 360 "array" ( arglist(literals 1, literals 2, literals 3, literals 4, literals 5) )  
arginit variable $d = constante false 
arginit variable $e = literals   };
          block 
          0 : 
              affectation 
              droite : 
                  variable $x
               "=" 
              gauche : 
                  literals 1
