Working on file 'tests/tokenizeur/scripts/foreach.41.test.php'
tests/tokenizeur/scripts/foreach.41.test.php
  codephp <?php

  code : 
      _foreach (property variable $a->literals b as  => variable $c)
          block 
          0 : 
              affectation 
              droite : 
                  property variable $thisliterals d->
              277 "+=" 
              gauche : 
                  literals 3
