Travail sur le fichier tests/tokenizeur/scripts/foreach.27.test.php 
tests/tokenizeur/scripts/foreach.27.test.php
  codephp <?php

  code : 
      _foreach (cast (array) as variable 309 "$b" => variable 309 "$c")
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$c"
               "=" 
              gauche : 
                  literals 2
