Travail sur le fichier tests/tokenizeur/scripts/foreach.8.test.php 
tests/tokenizeur/scripts/foreach.8.test.php
  codephp <?php 
  code : 
      _foreach (tableau property variable 309 "$a"->literals b[literals 1] as variable 309 "$c" => variable 309 "$d")
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$x"
               "=" 
              gauche : 
                  literals 1
