Travail sur le fichier tests/tokenizeur/scripts/foreach.29.test.php 
tests/tokenizeur/scripts/foreach.29.test.php
  codephp <?php

  code : 
      _foreach (variable 309 "$a" as  => variable 309 "$c")
          block 
          0 : 
              method variable 309 "$this"
              appel de methode : functioncall 307 "d" ( arglist(literals 'e') ) : 
                  functioncall d
                  appel de fonction : d: 
                      arglist 
                      0 : 
                          literals 'e'
