Travail sur le fichier tests/tokenizeur/scripts/foreach.16.test.php 
tests/tokenizeur/scripts/foreach.16.test.php
  codephp <?php

  code : 
      _foreach (variable 309 "$x" as variable 309 "$y" => reference &variable 309 "$z")
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$t"
               "=" 
              gauche : 
                  literals 1
