Travail sur le fichier tests/tokenizeur/scripts/foreach.5.test.php 
tests/tokenizeur/scripts/foreach.5.test.php
  codephp <?php 
  code : 
      _foreach (tableau variable 309 "$a"[literals 1] as variable 309 "$b" => variable 309 "$c")
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$x"
               "=" 
              gauche : 
                  literals 1
