Travail sur le fichier tests/tokenizeur/scripts/foreach.8.test.php 
tests/tokenizeur/scripts/foreach.8.test.php
  codephp <?php 
  code : 
      _foreach (tableau property variable $a->literals b[literals 1] as variable $c => variable $d)
          block 
          0 : 
              affectation 
              droite : 
                  variable $x
               "=" 
              gauche : 
                  literals 1
