tests/tokenizeur/scripts/foreach.17.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $x
           "=" 
          gauche : 
              functioncall range
              function call : range: 
                  arglist 
                  0 : 
                      literals 1
                  1 : 
                      literals 3
      1 : 
          _foreach (variable $x as tableau variable $y[literals 1] => reference &tableau variable $z[literals 3])
              block 
              0 : 
                  functioncall print
                  function call : print: 
                      arglist 
                      0 : 
                          tableau
                              variable $y
                              literals 1
