Travail sur le fichier tests/tokenizeur/scripts/foreach.22.test.php 
tests/tokenizeur/scripts/foreach.22.test.php
  codephp <?php 
  code : 
      _foreach (variable 309 "$x" as variable 309 "$y" => variable 309 "$z")
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$x"
               "=" 
              gauche : 
                  literals 1
