Working on file 'tests/tokenizeur/scripts/foreach.12.test.php'
tests/tokenizeur/scripts/foreach.12.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          _foreach (variable $escape as  => variable $probe)
              block 
              0 : 
                  affectation 
                  droite : 
                      variable $pattern
                   "=" 
                  gauche : 
                      functioncall str_replace
                      appel de fonction : str_replace: 
                          arglist 
                          0 : 
                              variable $probe
                          1 : 
                              concatenation 
                              0 : 
                                  literals \\
                              1 : 
                                  variable $probe
                          2 : 
                              variable $pattern
      1 : 
          affectation 
          droite : 
              variable $pattern
           "=" 
          gauche : 
              functioncall str_replace
              appel de fonction : str_replace: 
                  arglist 
                  0 : 
                      literals ?*
                  1 : 
                      literals *
                  2 : 
                      variable $x
