Working on file 'tests/tokenizeur/scripts/foreach.3.test.php'
tests/tokenizeur/scripts/foreach.3.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparaison property tableau variable $_SESSION[literals cligraph]->literals nbtuples 283 "==" literals 0" )
          block 
          0 : 
              affectation 
              droite : 
                  variable $date_mess_stock
               "=" 
              gauche : 
                  functioncall array
                  appel de fonction : array: 
                      arglist 
                      Liste d'argument vide
       else 
          block 
          0 : 
              affectation 
              droite : 
                  variable $i
               "=" 
              gauche : 
                  literals 0
          1 : 
              _foreach (variable $result2 as  => variable $ligne)
                  block 
                  0 : 
                      affectation 
                      droite : 
                          tableau
                              variable $date_mess_stock
                              variable $i
                       "=" 
                      gauche : 
                          tableau
                              variable $ligne
                              literals 0
                  1 : 
                      functioncall echo
                      appel de fonction : echo: 
                          arglist 
                          0 : 
                              concatenation 
                              0 : 
                                  literals <script language='javascript'>calend_valeur_stock[0][
                              1 : 
                                  variable $i
                              2 : 
                                  literals ]=\
                              3 : 
                                  tableau
                                      variable $date_mess_stock
                                      variable $i
                              4 : 
                                  literals \";</script>
                  2 : 
                      variable $i297 "++" 
                          variable $i
