Travail sur le fichier tests/tokenizeur/scripts/foreach.17.test.php 
tests/tokenizeur/scripts/foreach.17.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable 309 "$x"
           "=" 
          gauche : 
              functioncall range
              appel de fonction : range: 
                  arglist 
                  0 : 
                      literals 1
                  1 : 
                      literals 3
      1 : 
          _foreach (variable 309 "$x" as tableau variable 309 "$y"[literals 1] => reference &tableau variable 309 "$z"[literals 3])
              block 
              0 : 
                  functioncall print
                  appel de fonction : print: 
                      arglist 
                      0 : 
                          tableau
                              variable 309 "$y"
                              literals 1
