Travail sur le fichier tests/tokenizeur/scripts/foreach.28.test.php 
tests/tokenizeur/scripts/foreach.28.test.php
  codephp <?php

  code : 
      _foreach (variable $a as variable $b => variable $c)
          block 
          0 : 
              method variable $this
              appel de methode : functioncall 307 "d" ( arglist(literals 'e') ) : 
                  functioncall d
                  appel de fonction : d: 
                      arglist 
                      0 : 
                          literals 'e'
