Working on file 'tests/tokenizeur/scripts/foreach.21.test.php'
tests/tokenizeur/scripts/foreach.21.test.php
  codephp <?php 
  code : 
      _foreach (variable $x as variable $y => variable $z)
          block 
          0 : 
              affectation 
              droite : 
                  variable $x
               "=" 
              gauche : 
                  literals 1
          1 : 
              affectation 
              droite : 
                  variable $y
               "=" 
              gauche : 
                  literals 2
