tests/tokenizeur/scripts/function.18.test.php
  codephp <?php

  code : 
      function literals _getRules arglist(affectation variable $a  "=" constante null, affectation variable $b  "=" constante null, affectation variable $c  "=" constante null, affectation variable $d  "=" constante null, affectation variable $e  "=" constante null, affectation variable $f  "=" constante null)
          block 
