tests/tokenizeur/scripts/functioncall.51.test.php
  codephp <?php

  code : 
      ternaryop ?
      logical property variable $a->literals b  "&" constante C ? functioncall 300 "exit" ( arglist() )  : constante null
          logical 
          left : 
              property variable $aliterals b->
          operateur :  "&"
          right : 
              constante (              C )
          functioncall exit
          function call : 300 "exit": 
              arglist 
              0 : 
          constante (          null )
