tests/tokenizeur/scripts/functioncall.44.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $a
           "=" 
          gauche : 
              concatenation 
              0 : 
                  literals b
              1 : 
                  variable $c
      1 : 
          functioncall echo
          function call : echo: 
              arglist 
              0 : 
                  functioncall $d
                  function call : $d: 
                      arglist 
                      0 : 
                          _array
                              variable $e
                              variable $f
