tests/tokenizeur/scripts/functioncall.51.test.php
  codephp <?php

  code : 
      ternaryop ?
      logique property variable $a->literals b  "&" constante C ? functioncall 300 "exit" ( arglist() )  : constante null
          logique 
          droite : 
              property variable $aliterals b->
          operateur :  "&"
          gauche : 
              constante (              C )
          functioncall exit
          function call : exit: 
              arglist 
              0 : 
          constante (          null )
