tests/tokenizeur/scripts/functioncall.46.test.php
  rawtext 
  Texte : "311 " ""
  codephp <?php 
  code : 
      sequence 
      0 : 
          functioncall echo
          function call : echo: 
              arglist 
              0 : 
                  method variable $a
                  method call : functioncall 307 "b" ( arglist(variable $d) ) : 
                      functioncall b
                      function call : b: 
                          arglist 
                          0 : 
                              variable $d
      1 : 
          rawtext 
          Texte : "311 "(""
      2 : 
          functioncall echo
          function call : echo: 
              arglist 
              0 : 
                  method variable $e
                  method call : functioncall 307 "f" ( arglist(variable $g) ) : 
                      functioncall f
                      function call : f: 
                          arglist 
                          0 : 
                              variable $g
  rawtext 
  Texte : "311 ");
""
