tests/tokenizeur/scripts/functioncall.37.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $x
           "=" 
          gauche : 
              literals 3
      1 : 
          affectation 
          droite : 
              functioncall list
              function call : list: 
                  arglist 
                  0 : 
                      variable $x
                  1 : 
                      variable $y
                  2 : 
                      variable $z
           "=" 
          gauche : 
              functioncall range
              function call : range: 
                  arglist 
                  0 : 
                      literals 1
                  1 : 
                      literals 3
