Working on file 'tests/tokenizeur/scripts/functioncall.32.test.php'
tests/tokenizeur/scripts/functioncall.32.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          functioncall list
          appel de fonction : list: 
              arglist 
              0 : 
                  variable $x
              1 : 
                  variable $y
              2 : 
                  variable $z
       "=" 
      gauche : 
          functioncall range
          appel de fonction : range: 
              arglist 
              0 : 
                  literals 1
              1 : 
                  literals 3
