Working on file 'tests/tokenizeur/scripts/functioncall.47.test.php'
tests/tokenizeur/scripts/functioncall.47.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          noscream @
              functioncall list
              appel de fonction : list: 
                  arglist 
                  0 : 
                      variable $a
                  1 : 
                      variable $b
       "=" 
      gauche : 
          functioncall func_get_args
          appel de fonction : func_get_args: 
              arglist 
              Liste d'argument vide
