Travail sur le fichier tests/tokenizeur/scripts/function.13.test.php 
tests/tokenizeur/scripts/function.13.test.php
  codephp <?php

  code : 
      function literals a arglist(arginit reference &variable 309 "$b" = functioncall 360 "array" ( arglist(literals 1, clevaleur literals 2 => functioncall 360 "array" ( arglist(literals 3, literals 2) ) , literals 3) )  , affectation reference &variable 309 "$c"  "=" literals 1, reference &variable 309 "$d")
          block 
          0 : 
              functioncall print_r
              appel de fonction : print_r: 
                  arglist 
                  0 : 
                      variable 309 "$b"
