tests/tokenizeur/scripts/functioncall.47.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          noscream @
              functioncall list
              function call : list: 
                  arglist 
                  0 : 
                      variable $a
                  1 : 
                      variable $b
       "=" 
      right : 
          functioncall func_get_args
          function call : func_get_args: 
              arglist 
              Empty arglist
