Travail sur le fichier tests/tokenizeur/scripts/function.18.test.php 
tests/tokenizeur/scripts/function.18.test.php
  codephp <?php

  code : 
      function literals _getRules arglist(arginit variable 309 "$a" = constante null , arginit variable 309 "$b" = constante null , arginit variable 309 "$c" = constante null , arginit variable 309 "$d" = constante null , arginit variable 309 "$e" = constante null , arginit variable 309 "$f" = constante null )
          block 
