Travail sur le fichier tests/tokenizeur/scripts/functioncall.40.test.php 
tests/tokenizeur/scripts/functioncall.40.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $histo_fct
           "=" 
          gauche : 
              concatenation 
              0 : 
                  literals insert_histo_
              1 : 
                  variable $type_doc
      1 : 
          functioncall $histo_fct
          appel de fonction : $histo_fct: 
              arglist 
              0 : 
                  variable $cde_id
              1 : 
                  literals 1
