tests/tokenizeur/scripts/functioncall.25.test.php
  codephp <?php

  code : 
      functioncall a
      function call : a: 
          arglist 
          0 : 
              functioncall b
              function call : b: 
                  arglist 
                  0 : 
                      functioncall c
                      function call : c: 
                          arglist 
                          0 : 
                              literals 1
                          1 : 
                              literals 2
                          2 : 
                              literals 3
