tests/tokenizeur/scripts/functioncall.41.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          functioncall list
          function call : list: 
              arglist 
              0 : 
                  property_static 307 "a"::_array variable $b[literals c]->
              1 : 
                  variable $d
       "=" 
      right : 
          method_static 
          307 "e"::functioncall 307 "f" ( ( ) ) : 
              functioncall f
              function call : f: 
                  arglist 
                  Liste d'argument vide
