Travail sur le fichier tests/tokenizeur/scripts/functioncall.24.test.php 
tests/tokenizeur/scripts/functioncall.24.test.php
  codephp <?php

  code : 
      functioncall a
      appel de fonction : a: 
          arglist 
          0 : 
              functioncall b
              appel de fonction : b: 
                  arglist 
                  0 : 
                      literals a
                  1 : 
                      literals b
