Travail sur le fichier tests/tokenizeur/scripts/functioncall.16.test.php 
tests/tokenizeur/scripts/functioncall.16.test.php
  codephp <?php

  code : 
      functioncall echo
      appel de fonction : echo: 
          arglist 
          0 : 
              literals 1
          1 : 
              operation 
              droite : 
                  constante (                  x )
              operation :  "+"
              gauche : 
                  literals 1
          2 : 
              literals  
