tests/tokenizeur/scripts/functioncall.35.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              tableau
                  variable $x
                  literals 1
           "=" 
          gauche : 
              literals phpinfo
      1 : 
          functioncall $x
          function call : $x: 
              arglist 
              Liste d'argument vide
