Working on file 'tests/tokenizeur/scripts/functioncall.39.test.php'
tests/tokenizeur/scripts/functioncall.39.test.php
  codephp <?php 
  code : 
      sequence 
      0 : 
          functioncall echo
          appel de fonction : echo: 
              arglist 
              0 : 
                  literals x
      1 : 
          rawtext 
          Texte : "311 "  <img src="""
      2 : 
          functioncall echo
          appel de fonction : echo: 
              arglist 
              0 : 
                  concatenation 
                  0 : 
                      functioncall fct_lien_page_custom
                      appel de fonction : fct_lien_page_custom: 
                          arglist 
                          0 : 
                              concatenation 
                              0 : 
                                  constante (                                  TYPE_DOMAINE )
                              1 : 
                                  literals /accueil_graph1_trt.php
                  1 : 
                      literals ?
                  2 : 
                      variable $chart1URL
      3 : 
          rawtext 
          Texte : "311 "" border="0" usemap="#map1" />""
      4 : 
          functioncall echo
          appel de fonction : echo: 
              arglist 
              0 : 
                  literals y
