tests/tokenizeur/scripts/functioncall.27.test.php
  codephp <?php

  code : 
      functioncall print
      function call : print: 
          arglist 
          0 : 
              concatenation 
              0 : 
                  literals a
              1 : 
                  literals b
              2 : 
                  tableau
                      variable $t
                      literals 3
