tests/tokenizeur/scripts/functioncall.35.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          left : 
              _array
                  variable $x
                  literals 1
           "=" 
          right : 
              literals phpinfo
      1 : 
          functioncall $x
          function call : $x: 
              arglist 
              Empty arglist
