Travail sur le fichier tests/tokenizeur/scripts/functioncall.30.test.php 
tests/tokenizeur/scripts/functioncall.30.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          functioncall define
          appel de fonction : define: 
              arglist 
              0 : 
                  literals 'TYPE_DOC'
              1 : 
                  constante (                  true )
      1 : 
          inclusion require
              functioncall fct_lien_page_custom
              appel de fonction : fct_lien_page_custom: 
                  arglist 
                  0 : 
                      concatenation 
                      0 : 
                          literals "tabindex/"
                      1 : 
                          constante (                          TYPE_DOC )
                      2 : 
                          literals ".php"
                  1 : 
                      literals "abs"
