Working on file 'tests/tokenizeur/scripts/functioncall.26.test.php'
tests/tokenizeur/scripts/functioncall.26.test.php
  codephp <?php

  code : 
      functioncall a
      appel de fonction : a: 
          arglist 
          0 : 
              functioncall b
              appel de fonction : b: 
                  arglist 
                  0 : 
                      functioncall c
                      appel de fonction : c: 
                          arglist 
                          0 : 
                              functioncall d
                              appel de fonction : d: 
                                  arglist 
                                  0 : 
                                      literals 1
                                  1 : 
                                      literals 2
                                  2 : 
                                      literals 3
                                  3 : 
                                      literals 4
