Working on file 'tests/tokenizeur/scripts/function.18.test.php'
tests/tokenizeur/scripts/function.18.test.php
  codephp <?php

  code : 
      function literals _getRules arglist(arginit variable $a = constante null , arginit variable $b = constante null , arginit variable $c = constante null , arginit variable $d = constante null , arginit variable $e = constante null , arginit variable $f = constante null )
          block 
