Travail sur le fichier tests/tokenizeur/scripts/functioncall.27.test.php 
tests/tokenizeur/scripts/functioncall.27.test.php
  codephp <?php

  code : 
      functioncall print
      appel de fonction : print: 
          arglist 
          0 : 
              concatenation 
              0 : 
                  literals 'a'
              1 : 
                  literals 'b'
              2 : 
                  tableau
                      variable 309 "$t"
                      literals 3
