tests/tokenizeur/scripts/ifthen.41.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "variable $a" )
          block 
          0 : 
              affectation 
              droite : 
                  property property variable $this->literals bliterals c->
               "=" 
              gauche : 
                  variable $d
       else 
          block 
          0 : 
              affectation 
              droite : 
                  variable $e
               "=" 
              gauche : 
                  functioncall f
                  function call : f: 
                      arglist 
                      Liste d'argument vide
