Working on file 'tests/tokenizeur/scripts/ifthen.17.test.php'
tests/tokenizeur/scripts/ifthen.17.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "logique comparaison logique comparaison logique comparaison variable $jj 282 "!=" literals  279 "&&" variable $mm 282 "!=" literals  279 "&&" variable $yy 282 "!=" literals  279 "&&" comparaison tableau tableau tableau variable $_SESSION[literals prmt_mdl][literals news][literals 0] 283 "==" literals 1" )
          block 
          0 : 
              affectation 
              droite : 
                  variable $x
               "=" 
              gauche : 
                  literals 3
