Travail sur le fichier tests/tokenizeur/scripts/ifthen.28.test.php 
tests/tokenizeur/scripts/ifthen.28.test.php
  codephp <?php 
  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "literals 1" )
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$x"
               "=" 
              gauche : 
                  literals 1
          1 : 
              rawtext 
              Texte : "311 "texte brut1
""
      Condition 1) 
          parentheses 
          ( "literals 1" )
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$y"
               "=" 
              gauche : 
                  literals 2
          1 : 
              rawtext 
              Texte : "311 "texte brut2

""
