Travail sur le fichier tests/tokenizeur/scripts/ifthen.31.test.php 
tests/tokenizeur/scripts/ifthen.31.test.php
  codephp <?php 
  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "literals 1" )
          block 
          0 : 
              affectation 
              droite : 
                  variable $x
               "=" 
              gauche : 
                  literals 1
          1 : 
              rawtext 
              Texte : "311 "texte brut1
""
       else 
          block 
          0 : 
              affectation 
              droite : 
                  variable $y
               "=" 
              gauche : 
                  literals 2
          1 : 
              rawtext 
              Texte : "311 "texte brut2

""
