Travail sur le fichier tests/tokenizeur/scripts/ifthen.36.test.php 
tests/tokenizeur/scripts/ifthen.36.test.php
  codephp <?php 
  code : 
      sequence 
      0 : 
          ifthen if
          Condition 0) 
              parentheses 
              ( "literals 1" )
              block 
              0 : 
                  affectation 
                  droite : 
                      variable 309 "$x"
                   "=" 
                  gauche : 
                      literals 1
           else 
              block 
              0 : 
                  _foreach (property variable 309 "$a"->literals b as  => variable 309 "$c")
                      block 
                      0 : 
                          ifthen if
                          Condition 0) 
                              parentheses 
                              ( "comparaison variable 309 "$d" 281 "===" constante null" )
                              block 
                              0 : 
                                  affectation 
                                  droite : 
                                      variable 309 "$e"[]
                                          variable 309 "$e"
                                   "=" 
                                  gauche : 
                                      reference &
                                           new 307 "f" arglist(literals '') 
                           else 
                              block 
                              0 : 
                                  affectation 
                                  droite : 
                                      variable 309 "$g"[]
                                          variable 309 "$g"
                                   "=" 
                                  gauche : 
                                      reference &
                                          functioncall h
                                          appel de fonction : h: 
                                              arglist 
                                              0 : 
                                                  variable 309 "$e"
      1 : 
          affectation 
          droite : 
              variable 309 "$dd"[]
                  variable 309 "$dd"
           "=" 
          gauche : 
              literals 1
