Travail sur le fichier tests/tokenizeur/scripts/ifthen.43.test.php 
tests/tokenizeur/scripts/ifthen.43.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          ifthen if
          Condition 0) 
              parentheses 
              ( "variable $a" )
              block 
              0 : 
                  affectation 
                  droite : 
                      tableau
                          tableau
                              property variable $bliterals c->
                              literals 0
                          literals "d"
                  273 ".=" 
                  gauche : 
                      literals "e"
      1 : 
          ifthen if
          Condition 0) 
              parentheses 
              ( "variable $a" )
              block 
              0 : 
                  affectation 
                  droite : 
                      tableau
                          property property variable $b->literals cliterals d->
                          literals "e"
                  273 ".=" 
                  gauche : 
                      literals "f"
