tests/tokenizeur/scripts/ifthen.33.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "method variable $a->functioncall 307 "b" ( ( ) ) " )
          block 
          0 : 
              affectation 
              droite : 
                  variable $c
               "=" 
              gauche : 
                  method variable $d
                  appel de methode : functioncall 307 "e" ( arglist(literals f) ) : 
                      functioncall e
                      appel de fonction : e: 
                          arglist 
                          0 : 
                              literals f
       else 
          block 
          0 : 
              affectation 
              droite : 
                  variable $g
               "=" 
              gauche : 
                  method variable $h
                  appel de methode : functioncall 307 "e" ( arglist(literals i) ) : 
                      functioncall e
                      appel de fonction : e: 
                          arglist 
                          0 : 
                              literals i
