tests/tokenizeur/scripts/ifthen.56.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "variable $x" )
          block 
          0 : 
              method_static 
              307 "z"::functioncall 307 "y" ( ( ) ) : 
                  functioncall y
                  function call : y: 
                      arglist 
                      Liste d'argument vide
       else 
          block 
          0 : 
              method_static 
              307 "a"::functioncall 307 "b" ( ( ) ) : 
                  functioncall b
                  function call : b: 
                      arglist 
                      Liste d'argument vide
