Travail sur le fichier tests/tokenizeur/scripts/ifthen.14.test.php 
tests/tokenizeur/scripts/ifthen.14.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "variable $condition1" )
          block 
          0 : 
              literals 'then1'
      Condition 1) 
          parentheses 
          ( "variable $condition2" )
          block 
          0 : 
              literals 'then2'
      Condition 2) 
          parentheses 
          ( "variable $condition3" )
          block 
          0 : 
              literals 'then3'
      Condition 3) 
          parentheses 
          ( "variable $condition4" )
          block 
          0 : 
              literals 'then4'
      Condition 4) 
          parentheses 
          ( "variable $condition5" )
          block 
          0 : 
              literals 'then5'
