Travail sur le fichier tests/tokenizeur/scripts/ifthen.38.test.php 
tests/tokenizeur/scripts/ifthen.38.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparaison variable $a 283 "==" literals b" )
          block 
          0 : 
              affectation 
              droite : 
                  property variable $cliterals d->
               "=" 
              gauche : 
                  method variable $e
                  appel de methode : functioncall 307 "f" ( ( ) ) : 
                      functioncall f
                      appel de fonction : f: 
                          arglist 
                          Liste d'argument vide
