Travail sur le fichier tests/tokenizeur/scripts/ifthen.38.test.php 
tests/tokenizeur/scripts/ifthen.38.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparaison variable 309 "$a" 283 "==" literals "b"" )
          block 
          0 : 
              affectation 
              droite : 
                  property variable 309 "$c"literals d->
               "=" 
              gauche : 
                  method variable 309 "$e"
                  appel de methode : functioncall 307 "f" ( ( ) ) : 
                      functioncall f
                      appel de fonction : f: 
                          arglist 
                          Liste d'argument vide
