tests/tokenizeur/scripts/ifthen.51.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparaison variable $a 283 "==" literals 0" )
          block 
          0 : 
              affectation 
              droite : 
                  variable $b
               "=" 
              gauche : 
                  literals 1
       else 
          block 
          0 : 
              ifthen if
              Condition 0) 
                  parentheses 
                  ( "comparaison variable $c 283 "==" literals 2" )
                  block 
                  0 : 
                      functioncall echo
                      appel de fonction : echo: 
                          arglist 
                          0 : 
                              literals 3
                  1 : 
                      ifthen if
                      Condition 0) 
                          parentheses 
                          ( "comparaison variable $d 283 "==" literals " )
                          block 
                          0 : 
                              affectation 
                              droite : 
                                  variable $e
                               "=" 
                              gauche : 
                                  literals 4
                       else 
                          block 
                          0 : 
                              affectation 
                              droite : 
                                  variable $f
                               "=" 
                              gauche : 
                                  literals 5
                  2 : 
                      affectation 
                      droite : 
                          variable $g
                       "=" 
                      gauche : 
                          literals 6
              Condition 1) 
                  parentheses 
                  ( "affectation variable $h  "=" literals 7" )
                  block 
