tests/tokenizeur/scripts/ifthen.50.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparaison variable $commentheader 283 "==" literals no" )
          block 
          0 : 
              functioncall echo
              appel de fonction : echo: 
                  arglist 
                  0 : 
                      literals <br>
      Condition 1) 
          parentheses 
          ( "comparaison variable $commentheader 283 "==" literals 1" )
          block 
          0 : 
              functioncall echo
              appel de fonction : echo: 
                  arglist 
                  0 : 
                      literals <br>
      Condition 2) 
          parentheses 
          ( "comparaison variable $commentheader 283 "==" literals 2" )
          block 
          0 : 
              functioncall echo
              appel de fonction : echo: 
                  arglist 
                  0 : 
                      literals <br>
      Condition 3) 
          parentheses 
          ( "comparaison variable $commentheader 283 "==" literals 3" )
          block 
          0 : 
              functioncall echo
              appel de fonction : echo: 
                  arglist 
                  0 : 
                      literals <br>
      Condition 4) 
          parentheses 
          ( "comparaison variable $commentheader 283 "==" literals 4" )
          block 
          0 : 
              functioncall echo
              appel de fonction : echo: 
                  arglist 
                  0 : 
                      literals <br>
