Travail sur le fichier tests/tokenizeur/scripts/ifthen.26.test.php 
tests/tokenizeur/scripts/ifthen.26.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparaison variable 309 "$x" 283 "==" literals 6" )
          block 
          0 : 
              _foreach (variable 309 "$x" as  => variable 309 "$y")
                  block 
                  0 : 
                      variable 309 "$x"296 "--" 
                          variable 309 "$x"
