Travail sur le fichier tests/tokenizeur/scripts/ifthen.19.test.php 
tests/tokenizeur/scripts/ifthen.19.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "variable $condition" )
          block 
          0 : 
              literals "a"
      Condition 1) 
          parentheses 
          ( "variable $condition2" )
          block 
          0 : 
              literals "b"
          1 : 
              literals "b1"
          2 : 
              literals "b2"
          3 : 
              literals "b3"
      Condition 2) 
          parentheses 
          ( "variable $condition3" )
          block 
          0 : 
              literals "c"
          1 : 
              literals "c1"
          2 : 
              literals "c2"
          3 : 
              literals "c3"
