Travail sur le fichier tests/tokenizeur/scripts/ifthen.3.test.php 
tests/tokenizeur/scripts/ifthen.3.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "variable $condition" )
          block 
          0 : 
              ifthen if
              Condition 0) 
                  parentheses 
                  ( "variable $condition2" )
                  block 
                  0 : 
                      literals "a"
