Travail sur le fichier tests/tokenizeur/scripts/ifthen.23.test.php 
tests/tokenizeur/scripts/ifthen.23.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparaison variable 309 "$x" 283 "==" literals 6" )
          block 
          0 : 
              ifthen if
              Condition 0) 
                  parentheses 
                  ( "comparaison variable 309 "$y" 283 "==" literals 1" )
                  block 
                  0 : 
                      affectation 
                      droite : 
                          variable 309 "$a"
                       "=" 
                      gauche : 
                          literals 1
