Travail sur le fichier tests/tokenizeur/scripts/ifthen.51.test.php 
tests/tokenizeur/scripts/ifthen.51.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparaison variable 309 "$a" 283 "==" literals 0" )
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$b"
               "=" 
              gauche : 
                  literals "1"
       else 
          block 
          0 : 
              ifthen if
              Condition 0) 
                  parentheses 
                  ( "comparaison variable 309 "$c" 283 "==" literals "2"" )
                  block 
                  0 : 
                      functioncall echo
                      appel de fonction : echo: 
                          arglist 
                          0 : 
                              literals "3"
                  1 : 
                      ifthen if
                      Condition 0) 
                          parentheses 
                          ( "comparaison variable 309 "$d" 283 "==" literals """ )
                          block 
                          0 : 
                              affectation 
                              droite : 
                                  variable 309 "$e"
                               "=" 
                              gauche : 
                                  literals 4
                       else 
                          block 
                          0 : 
                              affectation 
                              droite : 
                                  variable 309 "$f"
                               "=" 
                              gauche : 
                                  literals 5
                  2 : 
                      affectation 
                      droite : 
                          variable 309 "$g"
                       "=" 
                      gauche : 
                          literals "6"
              Condition 1) 
                  parentheses 
                  ( "arginit variable 309 "$h" = literals "7" " )
                  block 
