Working on file 'tests/tokenizeur/scripts/ifthen.5.test.php'
tests/tokenizeur/scripts/ifthen.5.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "variable $condition" )
          block 
          0 : 
              ifthen if
              Condition 0) 
                  parentheses 
                  ( "variable $condition2" )
                  block 
                  0 : 
                      literals a
       else 
          block 
          0 : 
              literals b
