tests/tokenizeur/scripts/ifthen.47.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "functioncall 307 "preg_match" ( arglist(variable $pattern, variable $path, variable $matches) ) " )
          block 
          0 : 
              _return 
              return : "tableau variable $matches[literals 1]"
       else 
          block 
          0 : 
              not !
                  sign  "-"literals 1
                      literals 1
