Working on file 'tests/tokenizeur/scripts/ifthen.36.test.php'
tests/tokenizeur/scripts/ifthen.36.test.php
  codephp <?php 
  code : 
      sequence 
      0 : 
          ifthen if
          Condition 0) 
              parentheses 
              ( "literals 1" )
              block 
              0 : 
                  affectation 
                  droite : 
                      variable $x
                   "=" 
                  gauche : 
                      literals 1
           else 
              block 
              0 : 
                  _foreach (property variable $a->literals b as  => variable $c)
                      block 
                      0 : 
                          ifthen if
                          Condition 0) 
                              parentheses 
                              ( "comparaison variable $d 281 "===" constante null" )
                              block 
                              0 : 
                                  affectation 
                                  droite : 
                                      variable $e[]
                                          variable $e
                                   "=" 
                                  gauche : 
                                      reference &
                                           new 307 "f" arglist(literals ) 
                           else 
                              block 
                              0 : 
                                  affectation 
                                  droite : 
                                      variable $g[]
                                          variable $g
                                   "=" 
                                  gauche : 
                                      reference &
                                          functioncall h
                                          appel de fonction : h: 
                                              arglist 
                                              0 : 
                                                  variable $e
      1 : 
          affectation 
          droite : 
              variable $dd[]
                  variable $dd
           "=" 
          gauche : 
              literals 1
