Travail sur le fichier tests/tokenizeur/scripts/ifthen.47.test.php 
tests/tokenizeur/scripts/ifthen.47.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "functioncall 307 "preg_match" ( arglist(variable 309 "$pattern", variable 309 "$path", variable 309 "$matches") ) " )
          block 
          0 : 
              _return 
              return : "tableau variable 309 "$matches"[literals 1]"
       else 
          block 
          0 : 
              not !
                  signe  "-"literals 1
                      literals 1
