tests/tokenizeur/scripts/ifthen.12.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "variable $condition" )
          block 
          0 : 
              literals a
      Condition 1) 
          parentheses 
          ( "variable $condition2" )
          block 
          0 : 
              literals b
       else 
          block 
          0 : 
              literals c
