Travail sur le fichier tests/tokenizeur/scripts/inclusion.13.test.php 
tests/tokenizeur/scripts/inclusion.13.test.php
  codephp <?php

  code : 
      noscream @
          inclusion include
              concatenation 
              0 : 
                  method variable 309 "$a"
                  appel de methode : functioncall 307 "b" ( ( ) ) : 
                      functioncall b
                      appel de fonction : b: 
                          arglist 
                          Liste d'argument vide
              1 : 
                  literals '/c.php'
