tests/tokenizeur/scripts/invert.4.test.php
  codephp <?php

  code : 
      functioncall error_reporting
      function call : error_reporting: 
          arglist 
          0 : 
              logique 
              left : 
                  functioncall error_reporting
                  function call : error_reporting: 
                      arglist 
                      Liste d'argument vide
              operateur :  "&"
              right : 
                  invert ~
                      constante (                      E_STRICT )
