Travail sur le fichier tests/tokenizeur/scripts/invert.8.test.php 
tests/tokenizeur/scripts/invert.8.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$mod"
      271 "&=" 
      gauche : 
          invert ~
              method_static 
              307 "y"::functioncall 307 "x" ( ( ) ) : 
                  functioncall x
                  appel de fonction : x: 
                      arglist 
                      Liste d'argument vide
