Working on file 'tests/tokenizeur/scripts/invert.4.test.php'
tests/tokenizeur/scripts/invert.4.test.php
  codephp <?php

  code : 
      functioncall error_reporting
      appel de fonction : error_reporting: 
          arglist 
          0 : 
              logique 
              droite : 
                  functioncall error_reporting
                  appel de fonction : error_reporting: 
                      arglist 
                      Liste d'argument vide
              operateur :  "&"
              gauche : 
                  invert ~
                      constante (                      E_STRICT )
