tests/tokenizeur/scripts/keyvalue.8.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          functioncall array
          function call : array: 
              arglist 
              0 : 
                  literals a => tableau variable $b[variable $c]
                      literals a
                      tableau
                          variable $b
                          variable $c
