Working on file 'tests/tokenizeur/scripts/literals.6.test.php'
tests/tokenizeur/scripts/literals.6.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          functioncall range
          appel de fonction : range: 
              arglist 
              0 : 
                  signe  "-"literals 1
                      literals 1
              1 : 
                  literals 2
