tests/tokenizeur/scripts/literals.7.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              tableau
                  variable $r
                  literals 0
           "=" 
          gauche : 
              literals 1
      1 : 
          functioncall echo
          function call : echo: 
              arglist 
              0 : 
                  concatenation 
                  0 : 
                      literals ABC
                  1 : 
                      tableau
                          variable $r
                          literals 0
