tests/tokenizeur/scripts/literals.5.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $x
           "=" 
          gauche : 
              sign  "-"literals 10
                  literals 10
      1 : 
          affectation 
          droite : 
              variable $x
           "=" 
          gauche : 
              sign  "-"literals 10
                  literals 10
      2 : 
          functioncall echo
          appel de fonction : echo: 
              arglist 
              0 : 
                  variable $x
