Travail sur le fichier tests/tokenizeur/scripts/literals.8.test.php 
tests/tokenizeur/scripts/literals.8.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              property variable $rliterals a->
           "=" 
          gauche : 
              literals 1
      1 : 
          functioncall echo
          appel de fonction : echo: 
              arglist 
              0 : 
                  concatenation 
                  0 : 
                      literals ABC
                  1 : 
                      property variable $rliterals a->
