Working on file 'tests/tokenizeur/scripts/literals.12.test.php'
tests/tokenizeur/scripts/literals.12.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          operation 
          droite : 
              parentheses 
              ( "operation variable $y  "/" signe  "-"literals 2" )
          operation :  "+"
          gauche : 
              literals 0.3
