tests/tokenizeur/scripts/logique.21.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          logique 
          left : 
              variable $x
          operateur :  "|"
          right : 
              variable $y
      1 : 
          logique 
          left : 
              variable $a
          operateur :  "|"
          right : 
              variable $b
      2 : 
          logique 
          left : 
              variable $c
          operateur :  "|"
          right : 
              variable $d
