Travail sur le fichier tests/tokenizeur/scripts/logique.37.test.php 
tests/tokenizeur/scripts/logique.37.test.php
  codephp <?php 
  code : 
      sequence 
      0 : 
          functioncall echo
          appel de fonction : echo: 
              arglist 
              0 : 
                  logique 
                  droite : 
                      parentheses 
                      ( "comparaison tableau variable 309 "$property"[literals 'emp_id'] 283 "==" signe  "-"literals 1" )
                  operateur :  "|"
                  gauche : 
                      cdtternaire ?
                      parentheses (comparaison tableau variable 309 "$property"[literals 'emp_id'] 283 "==" literals '') ? literals 'selected' : sequenceliterals ''
rawtext 311 "A"

                          parentheses 
                          ( "comparaison tableau variable 309 "$property"[literals 'emp_id'] 283 "==" literals ''" )
                          literals 'selected'
                          sequence 
                          0 : 
                              literals ''
                          1 : 
                              rawtext 
                              Texte : "311 "A""
      1 : 
          functioncall echo
          appel de fonction : echo: 
              arglist 
              0 : 
                  variable 309 "$lang_Admin_Property_Please_Select"
