tests/tokenizeur/scripts/logique.15.test.php
  codephp <?php

  code : 
      logique 
      droite : 
          property variable $thisliterals a->
      operateur : 263 "or"
      gauche : 
          affectation 
          droite : 
              property variable $thisliterals b->
           "=" 
          gauche : 
              method variable $this
              method call : functioncall 307 "c" ( ( ) ) : 
                  functioncall c
                  function call : c: 
                      arglist 
                      Liste d'argument vide
