Travail sur le fichier tests/tokenizeur/scripts/logique.30.test.php 
tests/tokenizeur/scripts/logique.30.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$a"
       "=" 
      gauche : 
          logique 
          droite : 
              functioncall b
              appel de fonction : b: 
                  arglist 
                  0 : 
                      variable 309 "$q"
          operateur : 263 "or"
          gauche : 
              affectation 
              droite : 
                  variable 309 "$x"
              273 ".=" 
              gauche : 
                  literals 's'
