Travail sur le fichier tests/tokenizeur/scripts/logique.21.test.php 
tests/tokenizeur/scripts/logique.21.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          logique 
          droite : 
              variable $x
          operateur :  "|"
          gauche : 
              variable $y
      1 : 
          logique 
          droite : 
              variable $a
          operateur :  "|"
          gauche : 
              variable $b
      2 : 
          logique 
          droite : 
              variable $c
          operateur :  "|"
          gauche : 
              variable $d
