tests/tokenizeur/scripts/logique.35.test.php
  codephp <?php 
  code : 
      functioncall echo
      function call : echo: 
          arglist 
          0 : 
              logique 
              left : 
                  parentheses 
                  ( "literals 1" )
              operateur :  "|"
              right : 
                  parentheses 
                  ( "comparison _array variable $a[literals b] 283 "==" literals " )
