tests/tokenizeur/scripts/logique.8.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $a
       "=" 
      right : 
          logique 
          left : 
              method _array variable $b[literals c]
              method call : functioncall 307 "d" ( arglist(_array variable $e[literals 0]) ) : 
                  functioncall d
                  function call : d: 
                      arglist 
                      0 : 
                          _array
                              variable $e
                              literals 0
          operateur : 263 "or"
          right : 
              method _array variable $f[literals g]
              method call : functioncall 307 "h" ( ( ) ) : 
                  functioncall h
                  function call : h: 
                      arglist 
                      Liste d'argument vide
