Working on file 'tests/tokenizeur/scripts/logique.40.test.php'
tests/tokenizeur/scripts/logique.40.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          parentheses 
          ( "comparaison parentheses (logique method variable $b->functioncall 307 "c" ( arglist(variable $d) )  263 "or" property variable $e->literals f) 280 "!==" literals 5" )
