tests/tokenizeur/scripts/logique.14.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "logique literals 1 279 "&&" comparison _array property variable $a->literals b[variable $c] 281 "===" literals @" )
          block 
          0 : 
              affectation 
              droite : 
                  variable $x
               "=" 
              gauche : 
                  literals 1
