Travail sur le fichier tests/tokenizeur/scripts/logique.23.test.php 
tests/tokenizeur/scripts/logique.23.test.php
  codephp <?php

  code : 
      logique 
      droite : 
          tableau
              tableau
                  tableau
                      variable $a
                      literals b
                  property variable $dliterals e->
              literals f
      operateur :  "&"
      gauche : 
          property variable $gliterals h->
