tests/tokenizeur/scripts/logique.28.test.php
  codephp <?php

  code : 
      noscream @
          functioncall chmod
          function call : chmod: 
              arglist 
              0 : 
                  variable $fichier
              1 : 
                  logique 
                  left : 
                      constante (                      _SPIP_CHMOD )
                  operateur :  "&"
                  right : 
                      constante (                      PHPVERSION )
