Working on file 'tests/tokenizeur/scripts/logique.27.test.php'
tests/tokenizeur/scripts/logique.27.test.php
  codephp <?php

  code : 
      noscream @
          functioncall chmod
          appel de fonction : chmod: 
              arglist 
              0 : 
                  variable $fichier
              1 : 
                  logique 
                  droite : 
                      constante (                      _SPIP_CHMOD )
                  operateur :  "^"
                  gauche : 
                      literals 0666
