tests/tokenizeur/scripts/logique.8.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $a
       "=" 
      gauche : 
          logique 
          droite : 
              method tableau variable $b[literals c]
              method call : functioncall 307 "d" ( arglist(tableau variable $e[literals 0]) ) : 
                  functioncall d
                  function call : d: 
                      arglist 
                      0 : 
                          tableau
                              variable $e
                              literals 0
          operateur : 263 "or"
          gauche : 
              method tableau variable $f[literals g]
              method call : functioncall 307 "h" ( ( ) ) : 
                  functioncall h
                  function call : h: 
                      arglist 
                      Liste d'argument vide
