Travail sur le fichier tests/tokenizeur/scripts/logique.42.test.php 
tests/tokenizeur/scripts/logique.42.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "logique logique logique logique logique constante A  "&" variable $b 278 "||" constante C  "&" variable $d 278 "||" constante E  "&" variable $f" )
          block 
          0 : 
              affectation 
              droite : 
                  variable $g
               "=" 
              gauche : 
                  literals 1
