tests/tokenizeur/scripts/logique.17.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          property variable $thisliterals z->
       "=" 
      gauche : 
          logique 
          droite : 
              method variable $this
              method call : functioncall 307 "a" ( ( ) ) : 
                  functioncall a
                  function call : a: 
                      arglist 
                      Liste d'argument vide
          operateur : 263 "or"
          gauche : 
              affectation 
              droite : 
                  property variable $thisliterals b->
               "=" 
              gauche : 
                  method_static 
                  307 "d"::functioncall 307 "c" ( ( ) ) : 
                      functioncall c
                      function call : c: 
                          arglist 
                          Liste d'argument vide
