Travail sur le fichier tests/tokenizeur/scripts/logique.41.test.php 
tests/tokenizeur/scripts/logique.41.test.php
  codephp <?php 
  code : 
      logique 
      droite : 
          functioncall die
          appel de fonction : die: 
              arglist 
              0 : 
                  literals 1
      operateur :  "|"
      gauche : 
          parentheses 
          ( "comparaison tableau variable 309 "$a"[literals 'b'] 283 "==" literals ''" )
