tests/tokenizeur/scripts/logical.30.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $a
       "=" 
      right : 
          logical 
          left : 
              functioncall b
              function call : b: 
                  arglist 
                  0 : 
                      variable $q
          operateur : 263 "or"
          right : 
              affectation 
              left : 
                  variable $x
              273 ".=" 
              right : 
                  literals s
