tests/tokenizeur/scripts/logique.31.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $a
       "=" 
      right : 
          logique 
          left : 
              functioncall b
              function call : b: 
                  arglist 
                  0 : 
                      variable $q
          operateur : 263 "or"
          right : 
              affectation 
              left : 
                  variable $x
              277 "+=" 
              right : 
                  literals 2
