tests/tokenizeur/scripts/logique.45.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          logique 
          droite : 
              tableau
                  variable $a
                  concatenation 
                  0 : 
                      literals b
                  1 : 
                      variable $c
                  2 : 
                      literals d
          operateur : 279 "&&"
          gauche : 
              comparison 
              droite : 
                  variable $e
              operateur :  ">"
              gauche : 
                  literals 3
