tests/tokenizeur/scripts/logique.32.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $a
       "=" 
      gauche : 
          logique 
          droite : 
              functioncall b
              function call : b: 
                  arglist 
                  0 : 
                      variable $q
          operateur : 263 "or"
          gauche : 
              affectation 
              droite : 
                  variable $x
              276 "-=" 
              gauche : 
                  literals 2
