tests/tokenizeur/scripts/method_static.6.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $result
       "=" 
      gauche : 
          method_static 
          307 "parent"::functioncall variable $a ( arglist(variable $b, variable $c, variable $d) ) : 
              functioncall $a
              function call : $a: 
                  arglist 
                  0 : 
                      variable $b
                  1 : 
                      variable $c
                  2 : 
                      variable $d
