Working on file 'tests/tokenizeur/scripts/method.17.test.php'
tests/tokenizeur/scripts/method.17.test.php
  codephp <?php

  code : 
      functioncall echo
      appel de fonction : echo: 
          arglist 
          0 : 
              method variable $a
              appel de methode : functioncall 307 "b" ( ( ) ) : 
                  functioncall b
                  appel de fonction : b: 
                      arglist 
                      Liste d'argument vide
