Travail sur le fichier tests/tokenizeur/scripts/method.16.test.php 
tests/tokenizeur/scripts/method.16.test.php
  codephp <?php 
  code : 
      functioncall echo
      appel de fonction : echo: 
          arglist 
          0 : 
              method variable 309 "$d"
              appel de methode : functioncall 307 "a" ( arglist(variable 309 "$b") ) : 
                  functioncall a
                  appel de fonction : a: 
                      arglist 
                      0 : 
                          variable 309 "$b"
