Travail sur le fichier tests/tokenizeur/scripts/method.9.test.php 
tests/tokenizeur/scripts/method.9.test.php
  codephp <?php

  code : 
      method variable 309 "$e"
      appel de methode : functioncall 0 "." ( arglist(literals 1, literals 2) ) : 
          functioncall .
          appel de fonction : .: 
              arglist 
              0 : 
                  literals 1
              1 : 
                  literals 2
