Travail sur le fichier tests/tokenizeur/scripts/method.9.test.php 
tests/tokenizeur/scripts/method.9.test.php
  codephp <?php

  code : 
      method variable $e
      appel de methode : functioncall concatenation literals 'namespace1:gt' . literals '3' . literals '4'   ( arglist(literals 1, literals 2) ) : 
          functioncall .
          appel de fonction : .: 
              arglist 
              0 : 
                  literals 1
              1 : 
                  literals 2
