tests/tokenizeur/scripts/method_static.3.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $a
       "=" 
      gauche : 
          method method method_static 307 "b"::functioncall 307 "c" ( ( ) ) ->functioncall 307 "d" ( arglist(functioncall 360 "array" ( arglist(clevaleur literals e => functioncall 360 "array" ( arglist(clevaleur literals f => literals g) ) ) ) ) ) 
          appel de methode : functioncall 307 "h" ( ( ) ) : 
              functioncall h
              appel de fonction : h: 
                  arglist 
                  Liste d'argument vide
