tests/tokenizeur/scripts/method.15.test.php
  codephp <?php

  code : 
      functioncall strlen
      function call : strlen: 
          arglist 
          0 : 
              method variable $e
              method call : functioncall literals namespace1:gt ( arglist() ) : 
                  functioncall namespace1:gt
                  function call : namespace1:gt: 
                      arglist 
                      0 : 
