Working on file 'tests/tokenizeur/scripts/method.16.test.php'
tests/tokenizeur/scripts/method.16.test.php
  codephp <?php 
  code : 
      functioncall echo
      appel de fonction : echo: 
          arglist 
          0 : 
              method variable $d
              appel de methode : functioncall 307 "a" ( arglist(variable $b) ) : 
                  functioncall a
                  appel de fonction : a: 
                      arglist 
                      0 : 
                          variable $b
