tests/tokenizeur/scripts/method.16.test.php
  codephp <?php 
  code : 
      functioncall echo
      function call : echo: 
          arglist 
          0 : 
              method variable $d
              method call : functioncall 307 "a" ( arglist(variable $b) ) : 
                  functioncall a
                  function call : a: 
                      arglist 
                      0 : 
                          variable $b
