Travail sur le fichier tests/tokenizeur/scripts/method.6.test.php 
tests/tokenizeur/scripts/method.6.test.php
  codephp <?php

  code : 
      method variable $rech
      appel de methode : functioncall 307 "fct_rech_pdt" ( arglist(literals 3, literals 1, literals 2) ) : 
          functioncall fct_rech_pdt
          appel de fonction : fct_rech_pdt: 
              arglist 
              0 : 
                  literals 3
              1 : 
                  literals 1
              2 : 
                  literals 2
