tests/tokenizeur/scripts/namespace.4.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          function literals a arglist(typehint 0 "\" affectation variable $c  "=" constante null)
              block 
      1 : 
          function literals d arglist(typehint 0 "\" variable $f)
              block 
      2 : 
          function literals g arglist(typehint 0 "\" variable $j)
              block 
      3 : 
          function literals k arglist(typehint 0 "\" affectation variable $n  "=" constante null)
              block 
