tests/tokenizeur/scripts/noscream.18.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $a
       "=" 
      gauche : 
          noscream @
              _array
                  variable $b
                  operation 
                  droite : 
                      variable $i
                  operation :  "+"
                  gauche : 
                      literals 1
