Working on file 'tests/tokenizeur/scripts/noscream.12.test.php'
tests/tokenizeur/scripts/noscream.12.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          noscream @
              297 "++"tableau variable $a[literals b] 
                  tableau
                      variable $a
                      literals b
      1 : 
          noscream @
              296 "--"variable $i 
                  variable $i
