Travail sur le fichier tests/tokenizeur/scripts/noscream.13.test.php 
tests/tokenizeur/scripts/noscream.13.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$x"
       "=" 
      gauche : 
          concatenation 
          0 : 
              variable variable 309 "$a"
          1 : 
              literals /
          2 : 
              property variable 309 "$b"literals c->
          3 : 
              variable variable 309 "$d"
          4 : 
              literals @
          5 : 
              property variable 309 "$e"literals f->
