tests/tokenizeur/scripts/noscream.8.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $functions
       "=" 
      gauche : 
          ternaryop ?
          noscream @ ? literals  : literals bzopen
              noscream @
                  functioncall function_exists
                  function call : function_exists: 
                      arglist 
                      0 : 
                          literals bzopen
              literals 
              literals bzopen
