Travail sur le fichier tests/tokenizeur/scripts/noscream.12.test.php 
tests/tokenizeur/scripts/noscream.12.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          noscream @
              297 "++"tableau variable 309 "$a"[literals 'b'] 
                  tableau
                      variable 309 "$a"
                      literals 'b'
      1 : 
          noscream @
              296 "--"variable 309 "$i" 
                  variable 309 "$i"
