Travail sur le fichier tests/tokenizeur/scripts/noscream.11.test.php 
tests/tokenizeur/scripts/noscream.11.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          noscream @
              tableau variable $a[literals 'b']297 "++" 
                  tableau
                      variable $a
                      literals 'b'
      1 : 
          noscream @
              variable $i296 "--" 
                  variable $i
