Travail sur le fichier tests/tokenizeur/scripts/noscream.11.test.php 
tests/tokenizeur/scripts/noscream.11.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          noscream @
              tableau variable 309 "$a"[literals 'b']297 "++" 
                  tableau
                      variable 309 "$a"
                      literals 'b'
      1 : 
          noscream @
              variable 309 "$i"296 "--" 
                  variable 309 "$i"
