Travail sur le fichier tests/tokenizeur/scripts/noscream.9.test.php 
tests/tokenizeur/scripts/noscream.9.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          property variable 309 "$this"literals a->
       "=" 
      gauche : 
          noscream @
              functioncall $b
              appel de fonction : $b: 
                  arglist 
                  0 : 
                      concatenation 
                      0 : 
                          variable 309 "$host"
                      1 : 
                          literals 'a'
                  1 : 
                      literals 'b'
