Travail sur le fichier tests/tokenizeur/scripts/not.6.test.php 
tests/tokenizeur/scripts/not.6.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "not !" )
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$x"
               "=" 
              gauche : 
                  literals 1
