Travail sur le fichier tests/tokenizeur/scripts/not.7.test.php 
tests/tokenizeur/scripts/not.7.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          concatenation 
          0 : 
              variable variable $a
          1 : 
              literals /
          2 : 
              property variable $bliterals c->
          3 : 
              variable variable $d
          4 : 
              literals !
          5 : 
              property variable $eliterals f->
