Travail sur le fichier tests/tokenizeur/scripts/operation.14.test.php 
tests/tokenizeur/scripts/operation.14.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$x"
       "=" 
      gauche : 
          operation 
          droite : 
              property variable 309 "$a"literals b->
          operation :  "+"
          gauche : 
              property variable 309 "$c"literals d->
