Working on file 'tests/tokenizeur/scripts/operation.16.test.php'
tests/tokenizeur/scripts/operation.16.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          operation 
          droite : 
              property variable $aliterals b->
          operation :  "+"
          gauche : 
              property property variable $c->literals dliterals e->
