Travail sur le fichier tests/tokenizeur/scripts/operation.41.test.php 
tests/tokenizeur/scripts/operation.41.test.php
  codephp <?php

  code : 
      operation 
      droite : 
          variable $a
      operation :  "*"
      gauche : 
          affectation 
          droite : 
              variable $b
           "=" 
          gauche : 
              parentheses 
              ( "operation variable $c  "-" literals 2" )
