Working on file 'tests/tokenizeur/scripts/operation.29.test.php'
tests/tokenizeur/scripts/operation.29.test.php
  codephp <?php 
  code : 
      affectation 
      droite : 
          variable $a
      277 "+=" 
      gauche : 
          operation 
          droite : 
              property_static 307 "self"::tableau variable $b[variable $c]->
          operation :  "+"
          gauche : 
              literals 86400
