Working on file 'tests/tokenizeur/scripts/operation.15.test.php'
tests/tokenizeur/scripts/operation.15.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          operation 
          droite : 
              property variable $aliterals b->
          operation :  "*"
          gauche : 
              property variable $cliterals d->
