Working on file 'tests/tokenizeur/scripts/operation.5.test.php'
tests/tokenizeur/scripts/operation.5.test.php
  codephp <?php

  code : 
      operation 
      droite : 
          operation 
          droite : 
              operation 
              droite : 
                  literals 1
              operation :  "+"
              gauche : 
                  literals 1
          operation :  "+"
          gauche : 
              literals 1
      operation :  "+"
      gauche : 
          literals 1
