Working on file 'tests/tokenizeur/scripts/operation.47.test.php'
tests/tokenizeur/scripts/operation.47.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          operation 
          droite : 
              operation 
              droite : 
                  parentheses 
                  ( "operation property variable $c->literals y  "-" property property variable $a->literals b->literals c" )
              operation :  "*"
              gauche : 
                  operation 
                  droite : 
                      property variable $dliterals e->
                  operation :  "+"
                  gauche : 
                      property property variable $f->literals gliterals h->
          operation :  "+"
          gauche : 
              operation 
              droite : 
                  property variable $iliterals j->
              operation :  "*"
              gauche : 
                  parentheses 
                  ( "operation literals 1  "-" variable $k" )
