Travail sur le fichier tests/tokenizeur/scripts/operation.11.test.php 
tests/tokenizeur/scripts/operation.11.test.php
  codephp <?php

  code : 
      operation 
      droite : 
          parentheses 
          ( "operation literals 1  "+" literals 2" )
      operation :  "-"
      gauche : 
          parentheses 
          ( "operation literals 3  "*" operation parentheses (operation literals 4  "/" literals 5)  "%" literals 7" )
