Travail sur le fichier tests/tokenizeur/scripts/operation.25.test.php 
tests/tokenizeur/scripts/operation.25.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$x"
       "=" 
      gauche : 
          concatenation 
          0 : 
              property variable 309 "$this"literals a->
          1 : 
              literals +
          2 : 
              variable 309 "$b"
