tests/tokenizeur/scripts/operation.7.test.php
  codephp <?php

  code : 
      operation 
      left : 
          operation 
          left : 
              operation 
              left : 
                  literals 1
              operation :  "+"
              right : 
                  literals 1
          operation :  "-"
          right : 
              literals 1
      operation :  "+"
      right : 
          parentheses 
          ( "operation literals 1  "-" literals 1" )
