Travail sur le fichier tests/tokenizeur/scripts/operation.47.test.php 
tests/tokenizeur/scripts/operation.47.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$x"
       "=" 
      gauche : 
          operation 
          droite : 
              operation 
              droite : 
                  parentheses 
                  ( "operation property variable 309 "$c"->literals y  "-" property property variable 309 "$a"->literals b->literals c" )
              operation :  "*"
              gauche : 
                  operation 
                  droite : 
                      property variable 309 "$d"literals e->
                  operation :  "+"
                  gauche : 
                      property property variable 309 "$f"->literals gliterals h->
          operation :  "+"
          gauche : 
              operation 
              droite : 
                  property variable 309 "$i"literals j->
              operation :  "*"
              gauche : 
                  parentheses 
                  ( "operation literals 1  "-" variable 309 "$k"" )
