Travail sur le fichier tests/tokenizeur/scripts/operation.33.test.php 
tests/tokenizeur/scripts/operation.33.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $base
       "=" 
      gauche : 
          operation 
          droite : 
              operation 
              droite : 
                  variable $pad
              operation :  "+"
              gauche : 
                  variable $width
          operation :  "+"
          gauche : 
              variable $i297 "++" 
                  variable $i
