Travail sur le fichier tests/tokenizeur/scripts/operation.20.test.php 
tests/tokenizeur/scripts/operation.20.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$x1"
       "=" 
      gauche : 
          operation 
          droite : 
              variable 309 "$x1"
          operation :  "/"
          gauche : 
              operation 
              droite : 
                  method variable 309 "$this"
                  appel de methode : functioncall 307 "_size_col" ( arglist(variable 309 "$col_start") ) : 
                      functioncall _size_col
                      appel de fonction : _size_col: 
                          arglist 
                          0 : 
                              variable 309 "$col_start"
              operation :  "*"
              gauche : 
                  literals 1024
