tests/tokenizeur/scripts/operation.48.test.php
  codephp <?php 
  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "functioncall 350 "isset" ( arglist(tableau variable $x[method variable $y->functioncall 307 "z" ( ( ) ) ]) ) " )
          block 
          0 : 
              rawtext 
              Texte : "311 "    ""
          1 : 
              functioncall echo
              function call : echo: 
                  arglist 
                  0 : 
                      operation 
                      droite : 
                          method tableau variable $x[method variable $y->functioncall 307 "z" ( ( ) ) ]
                          method call : functioncall 307 "z" ( ( ) ) : 
                              functioncall z
                              function call : z: 
                                  arglist 
                                  Liste d'argument vide
                      operation :  "*"
                      gauche : 
                          literals 3
          2 : 
              rawtext 
              Texte : "311 """
      Condition 1) 
          parentheses 
          ( "constante true" )
          block 
          0 : 
              affectation 
              droite : 
                  variable $x
               "=" 
              gauche : 
                  literals 0
       else 
          block 
          0 : 
              rawtext 
              Texte : "311 "    0
""
