tests/tokenizeur/scripts/operation.31.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $a
       "=" 
      gauche : 
          operation 
          droite : 
              variable $b
          operation :  "+"
          gauche : 
              operation 
              droite : 
                  variable $c
              operation :  "*"
              gauche : 
                  variable $i296 "--" 
                      variable $i
