Working on file 'tests/tokenizeur/scripts/operation.13.test.php'
tests/tokenizeur/scripts/operation.13.test.php
  codephp <?php

  code : 
      operation 
      droite : 
          variable $x
      operation :  "*"
      gauche : 
          affectation 
          droite : 
              tableau
                  variable $y
                  literals 1
           "=" 
          gauche : 
              variable $z
