Travail sur le fichier tests/tokenizeur/scripts/operation.17.test.php 
tests/tokenizeur/scripts/operation.17.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$a"
       "=" 
      gauche : 
          functioncall strtolower
          appel de fonction : strtolower: 
              arglist 
              0 : 
                  tableau
                      variable 309 "$b"
                      operation 
                      droite : 
                          functioncall count
                          appel de fonction : count: 
                              arglist 
                              0 : 
                                  variable 309 "$c"
                      operation :  "-"
                      gauche : 
                          literals 1
