tests/tokenizeur/scripts/operation.21.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x1
       "=" 
      gauche : 
          operation 
          droite : 
              variable $x1
          operation :  "/"
          gauche : 
              operation 
              droite : 
                  method variable $this
                  method call : functioncall 307 "_size_col" ( arglist(variable $col_start) ) : 
                      functioncall _size_col
                      function call : _size_col: 
                          arglist 
                          0 : 
                              variable $col_start
              operation :  "+"
              gauche : 
                  literals 1024
