Working on file 'tests/tokenizeur/scripts/operation.37.test.php'
tests/tokenizeur/scripts/operation.37.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $base
       "=" 
      gauche : 
          operation 
          droite : 
              variable $pad
          operation :  "+"
          gauche : 
              operation 
              droite : 
                  variable $width
              operation :  "%"
              gauche : 
                  variable $i297 "++" 
                      variable $i
