Travail sur le fichier tests/tokenizeur/scripts/operation.27.test.php 
tests/tokenizeur/scripts/operation.27.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          concatenation 
          0 : 
              property variable $thisliterals a->
          1 : 
              literals %
          2 : 
              variable $b
