tests/tokenizeur/scripts/operation.17.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $a
       "=" 
      gauche : 
          functioncall strtolower
          appel de fonction : strtolower: 
              arglist 
              0 : 
                  tableau
                      variable $b
                      operation 
                      droite : 
                          functioncall count
                          appel de fonction : count: 
                              arglist 
                              0 : 
                                  variable $c
                      operation :  "-"
                      gauche : 
                          literals 1
