tests/tokenizeur/scripts/operation.49.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $a
       "=" 
      right : 
          operation 
          left : 
              variable $b
          operation :  "+"
          right : 
              method_static 
              0 "\"::functioncall 307 "d" ( arglist(variable $e) ) : 
                  functioncall d
                  function call : d: 
                      arglist 
                      0 : 
                          variable $e
