tests/tokenizeur/scripts/operation.38.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          operation 
          droite : 
              noscream @
                  functioncall number_format
                  function call : number_format: 
                      arglist 
                      0 : 
                          operation 
                          droite : 
                              variable $a
                          operation :  "/"
                          gauche : 
                              variable $b
                      1 : 
                          literals 2
          operation :  "*"
          gauche : 
              variable $c
