Working on file 'tests/tokenizeur/scripts/operation.44.test.php'
tests/tokenizeur/scripts/operation.44.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $a
           "=" 
          gauche : 
              literals 1
      1 : 
          operation 
          droite : 
              variable $a
          operation :  "*"
          gauche : 
              affectation 
              droite : 
                  variable $b
               "=" 
              gauche : 
                  parentheses 
                  ( "operation variable $c  "/" literals 2" )
