Working on file 'tests/tokenizeur/scripts/operation.22.test.php'
tests/tokenizeur/scripts/operation.22.test.php
  codephp <?php

  code : 
      operation 
      droite : 
          parentheses 
          ( "cdtternaire ?" )
      operation :  "*"
      gauche : 
          functioncall $sorter
          appel de fonction : $sorter: 
              arglist 
              0 : 
                  tableau
                      variable $a
                      tableau
                          variable $GLOBALS
                          literals callback_sort_by
              1 : 
                  tableau
                      variable $b
                      tableau
                          variable $GLOBALS
                          literals callback_sort_by
