Travail sur le fichier tests/tokenizeur/scripts/operation.31.test.php 
tests/tokenizeur/scripts/operation.31.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$a"
       "=" 
      gauche : 
          operation 
          droite : 
              variable 309 "$b"
          operation :  "+"
          gauche : 
              operation 
              droite : 
                  variable 309 "$c"
              operation :  "*"
              gauche : 
                  variable 309 "$i"296 "--" 
                      variable 309 "$i"
