tests/tokenizeur/scripts/property_static.11.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "comparison constante null 283 "==" affectation variable $a  "=" noscream @" )
          block 
          0 : 
              affectation 
              droite : 
                  variable $d
               "=" 
              gauche : 
                  literals 1
