Working on file 'tests/tokenizeur/scripts/property_static.10.test.php'
tests/tokenizeur/scripts/property_static.10.test.php
  codephp <?php

  code : 
      method method_static 307 "self"::functioncall 307 "a" ( ( ) ) 
      appel de methode : functioncall 307 "b" ( arglist(variable $c, variable $d) ) : 
          functioncall b
          appel de fonction : b: 
              arglist 
              0 : 
                  variable $c
              1 : 
                  variable $d
