Working on file 'tests/tokenizeur/scripts/property.14.test.php'
tests/tokenizeur/scripts/property.14.test.php
  codephp <?php

  code : 
      method property tableau property variable $a->literals b[literals 1]->tableau variable $c[literals 0]
      appel de methode : functioncall 307 "d" ( arglist(literals e, literals f) ) : 
          functioncall d
          appel de fonction : d: 
              arglist 
              0 : 
                  literals e
              1 : 
                  literals f
