Travail sur le fichier tests/tokenizeur/scripts/property.13.test.php 
tests/tokenizeur/scripts/property.13.test.php
  codephp <?php

  code : 
      method property property variable $a->literals b->tableau variable $c[literals 0]
      appel de methode : functioncall 307 "d" ( arglist(literals 'e', literals 'f') ) : 
          functioncall d
          appel de fonction : d: 
              arglist 
              0 : 
                  literals 'e'
              1 : 
                  literals 'f'
