Travail sur le fichier tests/tokenizeur/scripts/property_static.6.test.php 
tests/tokenizeur/scripts/property_static.6.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              property_static 307 "self"::tableau variable $a[literals b][]
                  property_static 307 "self"::tableau variable $a[literals b]->
           "=" 
          gauche : 
              variable $d
      1 : 
          affectation 
          droite : 
              property_static 307 "self"::tableau tableau variable $a[variable $b][literals 1][]
                  property_static 307 "self"::tableau tableau variable $a[variable $b][literals 1]->
           "=" 
          gauche : 
              variable $d
      2 : 
          affectation 
          droite : 
              property_static 307 "self"::tableau tableau tableau variable $a[variable $b][literals 1][constante true][]
                  property_static 307 "self"::tableau tableau tableau variable $a[variable $b][literals 1][constante true]->
           "=" 
          gauche : 
              variable $d
