tests/tokenizeur/scripts/property_static.3.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          affectation 
          droite : 
              property_static 307 "Y"::variable $C->
           "=" 
          gauche : 
              affectation 
              droite : 
                  variable $y
               "=" 
              gauche : 
                  literals 3
