tests/tokenizeur/scripts/rawtext.11.test.php
  rawtext 
  Texte : "311 "a
""
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $a
           "=" 
          gauche : 
              literals 1
      1 : 
          rawtext 
          Texte : "311 "b
""
      2 : 
          affectation 
          droite : 
              variable $b
           "=" 
          gauche : 
              literals 2
  rawtext 
  Texte : "311 "c""
