tests/tokenizeur/scripts/reference.9.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $a
       "=" 
      gauche : 
          reference &
              functioncall $b
              appel de fonction : $b: 
                  arglist 
                  0 : 
                      variable $c
                  1 : 
                      variable $d
                  2 : 
                      variable $e
