Travail sur le fichier tests/tokenizeur/scripts/reference.10.test.php 
tests/tokenizeur/scripts/reference.10.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          concatenation 
          0 : 
              literals a=
          1 : 
              variable variable $b
          2 : 
              literals &
          3 : 
              variable $c
          4 : 
              literals =
          5 : 
              variable variable $d
