Travail sur le fichier tests/tokenizeur/scripts/reference.9.test.php 
tests/tokenizeur/scripts/reference.9.test.php
  codephp <?php 
  code : 
      affectation 
      droite : 
          variable 309 "$a"
       "=" 
      gauche : 
          reference &
              functioncall $b
              appel de fonction : $b: 
                  arglist 
                  0 : 
                      variable 309 "$c"
                  1 : 
                      variable 309 "$d"
                  2 : 
                      variable 309 "$e"
