Travail sur le fichier tests/tokenizeur/scripts/return.7.test.php 
tests/tokenizeur/scripts/return.7.test.php
  codephp <?php

  code : 
      function literals cmp1 arglist(variable 309 "$a", variable 309 "$b")
          block 
          0 : 
              ifthen if
              Condition 0) 
                  parentheses 
                  ( "comparaison tableau variable 309 "$a"[literals 'fichier'] 283 "==" tableau variable 309 "$b"[literals 'fichier']" )
                  block 
                  0 : 
                      _return 
                      return : "literals 0"
