Travail sur le fichier tests/tokenizeur/scripts/sequence.16.test.php 
tests/tokenizeur/scripts/sequence.16.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          ifthen if
          Condition 0) 
              parentheses 
              ( "literals 1" )
              block 
              0 : 
                  inclusion include_once
                      concatenation 
                      0 : 
                          literals ./a
                      1 : 
                          literals /b.inc
           else 
              block 
              0 : 
                  affectation 
                  droite : 
                      variable $a
                   "=" 
                  gauche : 
                      literals 2
      1 : 
          affectation 
          droite : 
              variable $x
           "=" 
          gauche : 
              literals 1
