Working on file 'tests/tokenizeur/scripts/sequence.8.test.php'
tests/tokenizeur/scripts/sequence.8.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $x
           "=" 
          gauche : 
              literals 1
      1 : 
          rawtext 
          Texte : "311 "2
""
      2 : 
          affectation 
          droite : 
              variable $y
           "=" 
          gauche : 
              literals 3
