Travail sur le fichier tests/tokenizeur/scripts/sequence.9.test.php 
tests/tokenizeur/scripts/sequence.9.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          ifthen if
          Condition 0) 
              parentheses 
              ( "literals 1" )
              block 
              0 : 
                  affectation 
                  droite : 
                      variable $a
                   "=" 
                  gauche : 
                      literals 2
      1 : 
          rawtext 
          Texte : "311 " 3 ""
      2 : 
          affectation 
          droite : 
              variable $b
           "=" 
          gauche : 
              literals 3
