tests/tokenizeur/scripts/sequence.30.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $a
           "=" 
          gauche : 
              ternaryop ?
              parentheses (comparison variable $b 283 "==" literals 1) ? variable $d : variable $e
                  parentheses 
                  ( "comparison variable $b 283 "==" literals 1" )
                  variable $d
                  variable $e
      1 : 
          parentheses 
          ( "ternaryop ?" )
