tests/tokenizeur/scripts/sequence.26.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $a
           "=" 
          gauche : 
              literals 
      1 : 
          affectation 
          droite : 
              variable $b
           "=" 
          gauche : 
              literals c
      2 : 
          _for 
            Init : affectation variable $i  "=" literals 1;
            Fin  : comparison variable $i  "<" literals 3;
            Incr : postplusplus 297 "++"variable $i;
              block 
              0 : 
                  affectation 
                  droite : 
                      variable $f
                   "=" 
                  gauche : 
                      literals g
