tests/tokenizeur/scripts/sequence.27.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          left : 
              variable $s
           "=" 
          right : 
              comparison 
              left : 
                  functioncall intval
                  function call : intval: 
                      arglist 
                      0 : 
                          functioncall substr
                          function call : substr: 
                              arglist 
                              0 : 
                                  variable $a
                              1 : 
                                  literals 1
                              2 : 
                                  literals 2
              operateur :  "<"
              right : 
                  ternaryop ?
                  literals 12 ? literals c : literals d
                      literals 12
                      literals c
                      literals d
      1 : 
          _break 
          Number : " "1""
