Travail sur le fichier tests/tokenizeur/scripts/sequence.24.test.php 
tests/tokenizeur/scripts/sequence.24.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $a
           "=" 
          gauche : 
              literals 
      1 : 
          affectation 
          droite : 
              variable $b
           "=" 
          gauche : 
              literals c
      2 : 
          ifthen if
          Condition 0) 
              parentheses 
              ( "comparaison variable $d 288 "instanceof" constante e" )
              block 
              0 : 
                  affectation 
                  droite : 
                      variable $f
                   "=" 
                  gauche : 
                      literals g
