tests/tokenizeur/scripts/sequence.21.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $h
       "=" 
      gauche : 
          logique 
          droite : 
              functioncall a
              function call : a: 
                  arglist 
                  0 : 
                      functioncall b
                      function call : b: 
                          arglist 
                          0 : 
                              property variable $cliterals d->
          operateur :  "^"
          gauche : 
              functioncall e
              function call : e: 
                  arglist 
                  0 : 
                      property variable $fliterals g->
