Travail sur le fichier tests/tokenizeur/scripts/sequence.32.test.php 
tests/tokenizeur/scripts/sequence.32.test.php
  codephp <?php 
  code : 
      sequence 
      0 : 
          functioncall a
          appel de fonction : a: 
              arglist 
              0 : 
                  variable $b
      1 : 
          logique 
          droite : 
              comparaison 
              droite : 
                  functioncall c
                  appel de fonction : c: 
                      arglist 
                      0 : 
                          variable $d
              operateur : 282 "!="
              gauche : 
                  variable $e
          operateur : 279 "&&"
          gauche : 
              functioncall f
              appel de fonction : f: 
                  arglist 
                  0 : 
                      literals 'g'
      2 : 
          functioncall h
          appel de fonction : h: 
              arglist 
              0 : 
                  literals 'i'
