tests/tokenizeur/scripts/sequence.29.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $s
           "=" 
          gauche : 
              comparaison 
              droite : 
                  functioncall intval
                  function call : intval: 
                      arglist 
                      0 : 
                          functioncall substr
                          function call : substr: 
                              arglist 
                              0 : 
                                  variable $a
                              1 : 
                                  literals 1
                              2 : 
                                  literals 2
              operateur :  ">"
              gauche : 
                  cdtternaire ?
                  literals 12 ? literals c : literals d
                      literals 12
                      literals c
                      literals d
      1 : 
          _break 
          Nombre : " "1""
