Working on file 'tests/tokenizeur/scripts/sequence.22.test.php'
tests/tokenizeur/scripts/sequence.22.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $ignore
           "=" 
          gauche : 
              literals 1
      1 : 
          functioncall $errorfn
          appel de fonction : $errorfn: 
              arglist 
              0 : 
                  literals a
              1 : 
                  signe  "-"literals 9
                      literals 9
              2 : 
                  literals a
