tests/tokenizeur/scripts/sequence.11.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $a
           "=" 
          gauche : 
              literals a
      1 : 
          affectation 
          droite : 
              variable $b
           "=" 
          gauche : 
              literals b
      2 : 
          affectation 
          droite : 
              variable $c
           "=" 
          gauche : 
              literals c
      3 : 
          functioncall print
          function call : print: 
              arglist 
              0 : 
                  variable $c
