Working on file 'tests/tokenizeur/scripts/sequence.2.test.php'
tests/tokenizeur/scripts/sequence.2.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $a
           "=" 
          gauche : 
              literals 1
      1 : 
          affectation 
          droite : 
              variable $b
           "=" 
          gauche : 
              literals 2
