Travail sur le fichier tests/tokenizeur/scripts/sequence.2.test.php 
tests/tokenizeur/scripts/sequence.2.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable 309 "$a"
           "=" 
          gauche : 
              literals 1
      1 : 
          affectation 
          droite : 
              variable 309 "$b"
           "=" 
          gauche : 
              literals 2
