tests/tokenizeur/scripts/sequence.14.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          inclusion require_once
              literals a.php
      1 : 
          method method_static 307 "b"::functioncall 307 "c" ( arglist(literals d) ) 
          appel de methode : functioncall 307 "e" ( ( ) ) : 
              functioncall e
              appel de fonction : e: 
                  arglist 
                  Liste d'argument vide
