tests/tokenizeur/scripts/sequence.13.test.php
  codephp <?php

  code : 
      operation 
      droite : 
          parentheses 
          ( "operation tableau property variable $this->literals m_timeStamps[operation functioncall 307 "count" ( arglist(property variable $this->literals m_timeStamps) )   "-" literals 1]  "-" tableau property variable $this->literals m_timeStamps[literals 0]" )
      operation :  "/"
      gauche : 
          functioncall count
          function call : count: 
              arglist 
              0 : 
                  property variable $thisliterals m_timeStamps->
