Travail sur le fichier tests/tokenizeur/scripts/sequence.15.test.php 
tests/tokenizeur/scripts/sequence.15.test.php
  codephp <?php

  code : 
      function literals a arglist(variable 309 "$b", variable 309 "$c")
          block 
          0 : 
              affectation 
              droite : 
                  variable 309 "$z"
               "=" 
              gauche : 
                  literals 1
          1 : 
              affectation 
              droite : 
                  variable 309 "$y"
               "=" 
              gauche : 
                  literals 2
          2 : 
              affectation 
              droite : 
                  variable 309 "$w"
               "=" 
              gauche : 
                  literals 3
