Travail sur le fichier tests/tokenizeur/scripts/sequence.18.test.php 
tests/tokenizeur/scripts/sequence.18.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          noscream @
              functioncall fwrite
              appel de fonction : fwrite: 
                  arglist 
                  0 : 
                      variable 309 "$fp"
                  1 : 
                      literals 1
      1 : 
          noscream @
              functioncall fwrite
              appel de fonction : fwrite: 
                  arglist 
                  0 : 
                      variable 309 "$fp"
                  1 : 
                      literals 2
      2 : 
          noscream @
              functioncall fwrite
              appel de fonction : fwrite: 
                  arglist 
                  0 : 
                      variable 309 "$fp"
                  1 : 
                      literals 3
      3 : 
          noscream @
              functioncall fclose
              appel de fonction : fclose: 
                  arglist 
                  0 : 
                      variable 309 "$fp"
                  1 : 
                      literals 4
