tests/tokenizeur/scripts/sequence.34.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          functioncall a
          function call : a: 
              arglist 
              0 : 
                  variable $b
      1 : 
          logical 
          left : 
              comparison 
              left : 
                  functioncall c
                  function call : c: 
                      arglist 
                      0 : 
                          variable $d
              operateur : 282 "!="
              right : 
                  variable $e
          operateur : 265 "and"
          right : 
              functioncall f
              function call : f: 
                  arglist 
                  0 : 
                      literals g
      2 : 
          functioncall h
          function call : h: 
              arglist 
              0 : 
                  literals i
