tests/tokenizeur/scripts/sequence.44.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          method_static 
          307 "a"::functioncall 307 "b" ( ( ) ) : 
              functioncall b
              function call : b: 
                  arglist 
                  Empty arglist
      1 : 
          method_static 
          0 "\"::functioncall 307 "d" ( arglist(literals e, constante f) ) : 
              functioncall d
              function call : d: 
                  arglist 
                  0 : 
                      literals e
                  1 : 
                      constante (                      f )
