tests/tokenizeur/scripts/sequence.17.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $number
           "=" 
          gauche : 
              logique 
              droite : 
                  logique 
                  droite : 
                      parentheses 
                      ( "decalage functioncall 307 "ord" ( arglist(tableau variable $data[preplusplus variable $index297 "++"]) )   287 "<<"  literals 16 " )
                  operateur :  "|"
                  gauche : 
                      parentheses 
                      ( "decalage functioncall 307 "ord" ( arglist(tableau variable $data[preplusplus variable $index297 "++"]) )   287 "<<"  literals 8 " )
              operateur :  "|"
              gauche : 
                  functioncall ord
                  appel de fonction : ord: 
                      arglist 
                      0 : 
                          tableau
                              variable $data
                              297 "++"variable $index 
                                  variable $index
      1 : 
          _return 
          return : "variable $number"
