Working on file 'tests/tokenizeur/scripts/sequence.6.test.php'
tests/tokenizeur/scripts/sequence.6.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          functioncall print
          appel de fonction : print: 
              arglist 
              0 : 
                  literals 1
      1 : 
          functioncall print
          appel de fonction : print: 
              arglist 
              0 : 
                  literals 2
