tests/tokenizeur/scripts/sequence.35.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          functioncall a
          function call : a: 
              arglist 
              0 : 
                  variable $b
      1 : 
          logique 
          droite : 
              comparaison 
              droite : 
                  functioncall c
                  function call : c: 
                      arglist 
                      0 : 
                          variable $d
              operateur : 282 "!="
              gauche : 
                  variable $e
          operateur : 278 "||"
          gauche : 
              functioncall f
              function call : f: 
                  arglist 
                  0 : 
                      literals g
      2 : 
          functioncall h
          function call : h: 
              arglist 
              0 : 
                  literals i
