Working on file 'tests/tokenizeur/scripts/sequence.4.test.php'
tests/tokenizeur/scripts/sequence.4.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $a
           "=" 
          gauche : 
              literals 1
      1 : 
          affectation 
          droite : 
              variable $b
           "=" 
          gauche : 
              operation 
              droite : 
                  literals 1
              operation :  "+"
              gauche : 
                  literals 1
      2 : 
          affectation 
          droite : 
              variable $c
           "=" 
          gauche : 
              literals 3
