Travail sur le fichier tests/tokenizeur/scripts/sequence.26.test.php 
tests/tokenizeur/scripts/sequence.26.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable 309 "$a"
           "=" 
          gauche : 
              literals ''
      1 : 
          affectation 
          droite : 
              variable 309 "$b"
           "=" 
          gauche : 
              literals 'c'
      2 : 
          _for 
            Init : affectation variable 309 "$i"  "=" literals 1;
            Fin  : comparaison variable 309 "$i"  "<" literals 3;
            Incr : postplusplus 297 "++"variable 309 "$i";
              block 
              0 : 
                  affectation 
                  droite : 
                      variable 309 "$f"
                   "=" 
                  gauche : 
                      literals 'g'
