tests/tokenizeur/scripts/shell.3.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          functioncall strtolower
          appel de fonction : strtolower: 
              arglist 
              0 : 
                  shell 
                  0 : 
                      variable property variable $file->literals x
                  1 : 
                      literals  sf 
