tests/tokenizeur/scripts/sign.20.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $a
       "=" 
      gauche : 
          comparison 
          droite : 
              variable $b
          operateur : 283 "=="
          gauche : 
              operation 
              droite : 
                  operation 
                  droite : 
                      functioncall count
                      function call : count: 
                          arglist 
                          0 : 
                              variable $c
                  operation :  "-"
                  gauche : 
                      cdtternaire ?
                      literals 1 ? variable $d : variable $r
                          literals 1
                          variable $d
                          variable $r
              operation :  "+"
              gauche : 
                  variable $f
