tests/tokenizeur/scripts/sign.11.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $CurrNav
       "=" 
      gauche : 
          functioncall array
          appel de fonction : array: 
              arglist 
              0 : 
                  sign  "-"literals 3
                      literals 3
              1 : 
                  literals last => sign  "-"literals 1
                      literals last
                      sign  "-"literals 1
                          literals 1
              2 : 
                  sign  "-"literals 2
                      literals 2
