Working on file 'tests/tokenizeur/scripts/signe.14.test.php'
tests/tokenizeur/scripts/signe.14.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $tm
       "=" 
      gauche : 
          signe  "-"operation variable $tm  "*" variable $y
              operation 
              droite : 
                  variable $tm
              operation :  "*"
              gauche : 
                  variable $y
