tests/tokenizeur/scripts/sign.25.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          left : 
              variable $a
           "=" 
          right : 
              logique 
              left : 
                  variable $b
              operateur :  "&"
              right : 
                  sign  "-"literals 0xf
                      literals 0xf
      1 : 
          affectation 
          left : 
              variable $c
           "=" 
          right : 
              logique 
              left : 
                  variable $d
              operateur :  "|"
              right : 
                  sign  "-"literals 0xf
                      literals 0xf
