tests/tokenizeur/scripts/sign.10.test.php
  codephp <?php

  code : 
      functioncall print
      function call : print: 
          arglist 
          0 : 
              concatenation 
              0 : 
                  literals a
              1 : 
                  parentheses 
                  ( "operation operation parentheses (operation parentheses (operation variable $b  "-" variable $c)  "*" literals 2)  "+" parentheses (operation literals 3  "-" variable $d)  "+" variable $e" )
              2 : 
                  literals f
