Travail sur le fichier tests/tokenizeur/scripts/signe.9.test.php 
tests/tokenizeur/scripts/signe.9.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $a
       "=" 
      gauche : 
          functioncall substr
          appel de fonction : substr: 
              arglist 
              0 : 
                  variable $b
              1 : 
                  literals 0
              2 : 
                  operation 
                  droite : 
                      signe  "-"functioncall 307 "strlen" ( arglist(variable $c) ) 
                          functioncall strlen
                          appel de fonction : strlen: 
                              arglist 
                              0 : 
                                  variable $c
                  operation :  "-"
                  gauche : 
                      literals 1
