Working on file 'tests/tokenizeur/scripts/signe.11.test.php'
tests/tokenizeur/scripts/signe.11.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $CurrNav
       "=" 
      gauche : 
          functioncall array
          appel de fonction : array: 
              arglist 
              0 : 
                  signe  "-"literals 3
                      literals 3
              1 : 
                  literals last => signe  "-"literals 1
                      literals last
                      signe  "-"literals 1
                          literals 1
              2 : 
                  signe  "-"literals 2
                      literals 2
