Travail sur le fichier tests/tokenizeur/scripts/signe.12.test.php 
tests/tokenizeur/scripts/signe.12.test.php
  codephp <?php

  code : 
      functioncall print
      appel de fonction : print: 
          arglist 
          0 : 
              operation 
              droite : 
                  variable $a
              operation :  "-"
              gauche : 
                  signe  "+"signe  "+"signe  "-"signe  "+"signe  "+"variable $b
                      signe  "+"signe  "-"signe  "+"signe  "+"variable $b
                          signe  "-"signe  "+"signe  "+"variable $b
                              signe  "+"signe  "+"variable $b
                                  signe  "+"variable $b
                                      variable $b
