tests/tokenizeur/scripts/sign.17.test.php
  codephp <?php

  code : 
      ifthen if
      Condition 0) 
          parentheses 
          ( "logique comparison literals  283 "==" variable $a 278 "||" comparison sign  "+"literals 1 283 "==" variable $b" )
          block 
          0 : 
              affectation 
              droite : 
                  variable $x
               "=" 
              gauche : 
                  literals 1
