tests/tokenizeur/scripts/signe.21.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $u
       "=" 
      gauche : 
          signe  "-"cast (int)
              cast (295 "(int)")method variable $a->functioncall 307 "b" ( ( ) ) 
                  method variable $a
                  appel de methode : functioncall 307 "b" ( ( ) ) : 
                      functioncall b
                      appel de fonction : b: 
                          arglist 
                          Liste d'argument vide
