tests/tokenizeur/scripts/switch.17.test.php
  codephp <?php

  code : 
      _switch 
          parentheses 
          ( "variable $x" )
          block 
          0 : 
              _case 
                  literals 2
                  block 
                  0 : 
                      method variable $a
                      method call : functioncall 307 "b" ( ( ) ) : 
                          functioncall b
                          function call : b: 
                              arglist 
                              Liste d'argument vide
                  1 : 
                      affectation 
                      droite : 
                          property variable $cliterals d->
                       "=" 
                      gauche : 
                          constante (                          true )
                  2 : 
                      _break 
                      Number : " "1""
