Travail sur le fichier tests/tokenizeur/scripts/switch.19.test.php 
tests/tokenizeur/scripts/switch.19.test.php
  codephp <?php

  code : 
      _switch 
          parentheses 
          ( "variable $a" )
          block 
          0 : 
              _case 
                  literals "a"
                  block 
                  0 : 
                      affectation 
                      droite : 
                          variable $z
                       "=" 
                      gauche : 
                          literals 1
                  1 : 
                      _break 
                      Nombre : " "1""
          1 : 
              _default 
                  block 
                  0 : 
                      affectation 
                      droite : 
                          variable $z
                       "=" 
                      gauche : 
                          literals 3
                  1 : 
                      _break 
                      Nombre : " "1""
