Travail sur le fichier tests/tokenizeur/scripts/switch.21.test.php 
tests/tokenizeur/scripts/switch.21.test.php
  codephp <?php

  code : 
      _switch 
          parentheses 
          ( "variable 309 "$a"" )
          block 
          0 : 
              _case 
                  literals 'a'
                  block 
                  0 : 
                      _break 
                      Nombre : " "1""
          1 : 
              _case 
                  literals 'b'
                  block 
                  0 : 
                      _break 
                      Nombre : " "1""
          2 : 
              _case 
                  literals 'c'
                  block 
                  0 : 
                      _break 
                      Nombre : " "1""
          3 : 
              _case 
                  literals 'd'
                  block 
                  0 : 
                      _break 
                      Nombre : " "1""
          4 : 
              _default 
                  block 
                  0 : 
                      _break 
                      Nombre : " "1""
