Travail sur le fichier tests/tokenizeur/scripts/switch.17.test.php 
tests/tokenizeur/scripts/switch.17.test.php
  codephp <?php 
  code : 
      _switch 
          parentheses 
          ( "variable 309 "$x"" )
          block 
          0 : 
              _case 
                  literals 2
                  block 
                  0 : 
                      method variable 309 "$a"
                      appel de methode : functioncall 307 "b" ( ( ) ) : 
                          functioncall b
                          appel de fonction : b: 
                              arglist 
                              Liste d'argument vide
                  1 : 
                      affectation 
                      droite : 
                          property variable 309 "$c"literals d->
                       "=" 
                      gauche : 
                          constante (                          true )
                  2 : 
                      _break 
                      Nombre : " "1""
