tests/tokenizeur/scripts/switch.3.test.php
  codephp <?php

  code : 
      _switch 
          parentheses 
          ( "literals 1" )
          block 
          0 : 
              _case 
                  literals 2
                  block 
                  0 : 
                      affectation 
                      droite : 
                          variable $x
                       "=" 
                      gauche : 
                          literals 3
