Working on file 'tests/tokenizeur/scripts/switch.22.test.php'
tests/tokenizeur/scripts/switch.22.test.php
  codephp <?php

  code : 
      _switch 
          parentheses 
          ( "variable $a" )
          block 
          0 : 
              _case 
                  literals a
                  block 
          1 : 
              _case 
                  literals b
                  block 
          2 : 
              _case 
                  literals c
                  block 
          3 : 
              _case 
                  literals d
                  block 
                  0 : 
                      _break 
                      Nombre : " "1""
          4 : 
              _default 
                  block 
                  0 : 
                      _break 
                      Nombre : " "1""
