tests/tokenizeur/scripts/switch.29.test.php
  codephp <?php

  code : 
      _switch 
          parentheses 
          ( "constante true" )
          block 
          0 : 
              _case 
                  comparison 
                  left : 
                      property variable $aliterals b->
                  operateur : 281 "==="
                  right : 
                      constante (                      null )
                  block 
                  0 : 
                      _return 
                      return : "_new "
          1 : 
              _default 
                  block 
                  0 : 
                      _return 
                      return : "_new "
