Travail sur le fichier tests/tokenizeur/scripts/tableau.5.test.php 
tests/tokenizeur/scripts/tableau.5.test.php
  codephp <?php

  code : 
      tableau
          tableau
              variable $GLOBALS
              literals '_TABLE_CORRESPONDANCE_MENU'
          tableau
              variable $tb_menu_racc
              operation 
              droite : 
                  variable $i
              operation :  "-"
              gauche : 
                  literals 1
