tests/tokenizeur/scripts/ternaryop.31.test.php
  codephp <?php

  code : 
      affectation 
      left : 
          variable $a
       "=" 
      right : 
          ternaryop ?
          variable $b ? block { } : functioncall 0 "$c" ( arglist(literals D) ) 
              variable $b
              block 
              functioncall $c
              function call : 0 "$c": 
                  arglist 
                  0 : 
                      literals D
