tests/tokenizeur/scripts/ternaryop.20.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          left : 
              variable $_tag
           "=" 
          right : 
              ternaryop ?
              method variable $x->functioncall 307 "y" ( ( ) )  ? method variable $x->functioncall 307 "z" ( ( ) )  : comparison literals literal 0 "<" functioncall 316 "echo" ( arglist(variable $x) ) 
                  method variable $x
                  method call : functioncall 307 "y" ( ( ) ) : 
                      functioncall y
                      function call : y: 
                          arglist 
                          Empty arglist
                  method variable $x
                  method call : functioncall 307 "z" ( ( ) ) : 
                      functioncall z
                      function call : z: 
                          arglist 
                          Empty arglist
                  comparison 
                  left : 
                      literals literal
                  operateur : 0 "<"
                  right : 
                      functioncall echo
                      function call : echo: 
                          arglist 
                          0 : 
                              variable $x
      1 : 
          rawtext 
          Texte : "311 " id="""
      2 : 
          functioncall echo
          function call : echo: 
              arglist 
              0 : 
                  method variable $x
                  method call : functioncall 307 "w" ( ( ) ) : 
                      functioncall w
                      function call : w: 
                          arglist 
                          Empty arglist
      3 : 
          rawtext 
          Texte : "311 "" ""
      4 : 
          functioncall echo
          function call : echo: 
              arglist 
              0 : 
                  method variable $z
                  method call : functioncall 307 "d" ( ( ) ) : 
                      functioncall d
                      function call : d: 
                          arglist 
                          Empty arglist
      5 : 
          rawtext 
          Texte : "311 ">
""
      6 : 
          functioncall echo
          function call : echo: 
              arglist 
              0 : 
                  method variable $x
                  method call : functioncall 307 "x" ( ( ) ) : 
                      functioncall x
                      function call : x: 
                          arglist 
                          Empty arglist
      7 : 
          rawtext 
          Texte : "311 "</""
      8 : 
          functioncall echo
          function call : echo: 
              arglist 
              0 : 
                  variable $x
  rawtext 
  Texte : "311 ">""
