tests/tokenizeur/scripts/ternaryop.32.test.php
  codephp <?php

  code : 
      ternaryop ?
      functioncall 350 "isset" ( arglist(_array variable $a[literals b]) )  ? cast (bool) : constante false
          functioncall isset
          function call : 350 "isset": 
              arglist 
              0 : 
                  _array
                      variable $a
                      literals b
          cast (290 "(bool)")comparison _array variable $c[literals d] 282 "!=" constante true
              comparison 
              left : 
                  _array
                      variable $c
                      literals d
              operateur : 282 "!="
              right : 
                  constante (                  true )
          constante (          false )
