tests/tokenizeur/scripts/ternaryop.23.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          functioncall echo
          function call : echo: 
              arglist 
              0 : 
                  logical 
                  left : 
                      functioncall isset
                      function call : isset: 
                          arglist 
                          0 : 
                              _array
                                  property variable $thisliterals a->
                                  literals b
                  operateur : 279 "&&"
                  right : 
                      ternaryop ?
                      _array property variable $c->literals d[literals e] ? literals f : constante g
                          _array
                              property variable $cliterals d->
                              literals e
                          literals f
                          constante (                          g )
      1 : 
          rawtext 
          Texte : "311 "?""
      2 : 
          functioncall echo
          function call : echo: 
              arglist 
              0 : 
                  method variable $h
                  method call : functioncall 307 "i" ( ( ) ) : 
                      functioncall i
                      function call : i: 
                          arglist 
                          Empty arglist
