tests/tokenizeur/scripts/ternaryop.3.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $rech_ven
       "=" 
      gauche : 
          ternaryop ?
          functioncall 350 "isset" ( arglist(tableau variable $_REQUEST[literals rech_ven]) )  ? tableau variable $_REQUEST[literals rech_ven] : literals 
              functioncall isset
              function call : isset: 
                  arglist 
                  0 : 
                      tableau
                          variable $_REQUEST
                          literals rech_ven
              tableau
                  variable $_REQUEST
                  literals rech_ven
              literals 
