tests/tokenizeur/scripts/ternaryop.6.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $x
       "=" 
      gauche : 
          ternaryop ?
          literals 1 ? literals 2 : tableau tableau tableau variable $x[literals 1][literals 2][literals 3]
              literals 1
              literals 2
              tableau
                  tableau
                      tableau
                          variable $x
                          literals 1
                      literals 2
                  literals 3
