tests/tokenizeur/scripts/ternaryop.18.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable $a
       "=" 
      gauche : 
          ternaryop ?
          functioncall 351 "empty" ( arglist(variable $b) )  ? variable $d : affectation variable $d 273 ".=" concatenation literals   . variable $e  
              functioncall empty
              function call : empty: 
                  arglist 
                  0 : 
                      variable $b
              variable $d
              affectation 
              droite : 
                  variable $d
              273 ".=" 
              gauche : 
                  concatenation 
                  0 : 
                      literals  
                  1 : 
                      variable $e
