tests/tokenizeur/scripts/ternaryop.16.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          ifthen if
          Condition 0) 
              parentheses 
              ( "variable $x" )
              block 
              0 : 
                  affectation 
                  droite : 
                      variable $x
                   "=" 
                  gauche : 
                      literals 1
      1 : 
          ternaryop ?
          parentheses (functioncall 307 "function_exists" ( arglist(literals a) ) ) ? functioncall 307 "a" ( arglist(literals b) )  : literals 
              parentheses 
              ( "functioncall 307 "function_exists" ( arglist(literals a) ) " )
              functioncall a
              function call : a: 
                  arglist 
                  0 : 
                      literals b
              literals 
