tests/tokenizeur/scripts/ternaryop.13.test.php
  codephp <?php

  code : 
      _for 
        Init : affectation variable $b  "=" literals 0;
        Fin  : comparison variable $b  "<" literals 1;
        Incr : postplusplus 297 "++"variable $b;
          block 
          0 : 
              rawtext 
              Texte : "311 "TR ""
          1 : 
              functioncall echo
              function call : echo: 
                  arglist 
                  0 : 
                      ternaryop ?
                      functioncall 350 "isset" ( arglist(variable $a) )  ? literals desc : literals asc
                          functioncall isset
                          function call : isset: 
                              arglist 
                              0 : 
                                  variable $a
                          literals desc
                          literals asc
          2 : 
              rawtext 
              Texte : "311 " TR 
""
