Travail sur le fichier tests/tokenizeur/scripts/try.4.test.php 
tests/tokenizeur/scripts/try.4.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          _try 
              block 
          0 : 
              _catch (307 "Exception")variable 309 "$e"
                  block 
      1 : 
          affectation 
          droite : 
              variable 309 "$x"
           "=" 
          gauche : 
              literals 1
