Working on file 'tests/tokenizeur/scripts/try.4.test.php'
tests/tokenizeur/scripts/try.4.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          _try 
              block 
          0 : 
              _catch (307 "Exception")variable $e
                  block 
      1 : 
          affectation 
          droite : 
              variable $x
           "=" 
          gauche : 
              literals 1
