Travail sur le fichier tests/tokenizeur/scripts/try.1.test.php 
tests/tokenizeur/scripts/try.1.test.php
  codephp <?php

  code : 
      _try 
          block 
      0 : 
          _catch (307 "Exception")variable 309 "$e"
              block 
      1 : 
          _catch (307 "Exception1")variable 309 "$e"
              block 
      2 : 
          _catch (307 "Exception2")variable 309 "$e"
              block 
