Travail sur le fichier tests/tokenizeur/scripts/typehint.6.test.php 
tests/tokenizeur/scripts/typehint.6.test.php
  codephp <?php

  code : 
      affectation 
      droite : 
          variable 309 "$x"
       "=" 
      gauche : 
          concatenation 
          0 : 
              literals 'a: '
          1 : 
              functioncall base64_encode
              appel de fonction : base64_encode: 
                  arglist 
                  0 : 
                      concatenation 
                      0 : 
                          variable 309 "$b"
                      1 : 
                          literals ,
                      2 : 
                          variable 309 "$c"
                      3 : 
                          literals ,
                      4 : 
                          variable 309 "$d"
                      5 : 
                          literals ,e,
                      6 : 
                          tableau
                              variable 309 "$r"
                              constante (                              g )
          2 : 
              literals "\n"
