tests/tokenizeur/scripts/variable.10.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          affectation 
          droite : 
              variable $x
           "=" 
          gauche : 
              concatenation 
              0 : 
                  variable $y
      1 : 
          affectation 
          droite : 
              variable $x
           "=" 
          gauche : 
              concatenation 
              0 : 
                  variable variable z
      2 : 
          affectation 
          droite : 
              variable $x
           "=" 
          gauche : 
              concatenation 
              0 : 
                  variable variable $a
