tests/tokenizeur/scripts/while.14.test.php
  codephp <?php

  code : 
      _dowhile 
          block 
          0 : 
              affectation 
              left : 
                  variable $a
               "=" 
              right : 
                  functioncall sha1
                  function call : sha1: 
                      arglist 
                      0 : 
                          functioncall microtime
                          function call : microtime: 
                              arglist 
                              Empty arglist
          parentheses 
          ( "functioncall 307 "file_exists" ( arglist(concatenation variable $c . variable $d  ) ) " )
