tests/tokenizeur/scripts/while.10.test.php
  codephp <?php

  code : 
      _while 
          parentheses 
          ( "comparaison postplusplus 296 "--"variable $a  ">" literals 0" )
          block 
          0 : 
              affectation 
              droite : 
                  variable $b[]
                      variable $b
               "=" 
              gauche : 
                  concatenation 
                  0 : 
                      literals 
                  1 : 
                      tableau
                          variable $d
                          variable $e297 "++" 
                              variable $e
