Working on file 'tests/tokenizeur/scripts/while.4.test.php'
tests/tokenizeur/scripts/while.4.test.php
  codephp <?php

  code : 
      sequence 
      0 : 
          ifthen if
          Condition 0) 
              parentheses 
              ( "literals 1" )
              block 
              0 : 
                  literals 2
      1 : 
          _while 
              parentheses 
              ( "literals 4" )
              block 
              0 : 
                  literals 5
