Travail sur le fichier tests/tokenizeur/scripts/while.6.test.php 
tests/tokenizeur/scripts/while.6.test.php
  codephp <?php

  code : 
      _while 
          parentheses 
          ( "comparaison preplusplus variable $a296 "--" 284 ">=" literals 0" )
          block 
          0 : 
              method variable $this
              appel de methode : functioncall 307 "b" ( arglist(literals 'c') ) : 
                  functioncall b
                  appel de fonction : b: 
                      arglist 
                      0 : 
                          literals 'c'
