./tokenizeur.php  -r -d ./References/caceis-20100608/ -I ini/caceis.ini -g mysql,cache > log/caceis.log 
./tokenizeur.php  -r -d ./References/CodeIgniter_1.7.2/ -I ini/codeigniter.ini -g mysql,cache > log/codeigniter.log 
./tokenizeur.php  -r -d ./References/EECore1/ -I ini/expressionengine1.ini -g mysql,cache > log/expressionengine1.log
./tokenizeur.php  -r -d ./References/Discuz_7.2/ -I ini/discuz.ini -g mysql,cache > log/discuz.log 
./tokenizeur.php  -r -d ./References/dolibarr-2.8.1/ -I ini/dolibarr.ini -g mysql,cache > log/dolibarr.log 
./tokenizeur.php  -r -d ./References/dotclear/ -I ini/dotclear.ini -g mysql,cache > log/dotclear.log 
./tokenizeur.php  -r -d ./References/wordpress/ -I ini/wordpress.ini -g mysql,cache > log/wordpress.log 
./tokenizeur.php  -r -d ./References/phpMyAdmin-3.2.5/ -I ini/phpmyadmin.ini -g mysql,cache > log/phpmyadmin.log 
./tokenizeur.php  -r -d ./References/orangehrm-2.5.0.4/ -I ini/orangehrm.ini -g mysql,cache > log/orangehrm.log 
./tokenizeur.php  -r -d ./References/PHP_CodeBrowser-b588cde/ -I ini/phpcodebrowser.ini -g mysql,cache > log/phpcodebrowser.log 
./tokenizeur.php  -r -d ./References/PHPUnit-3.4.9/ -I ini/phpunit.ini -g mysql,cache > log/phpunit.log 
