<?php

true;
FALSE;
__METHOD__;
__FILE__;

CONSTANTE_USER;
$tableau[CONSTANTE_TABLEAU];
fonction(CONSTANTE_FONCTION1, CONSTANTE_FONCTION2, CONSTANTE_FONCTION3);
array(CONSTANTE_ARRAY1, CONSTANTE_ARRAY2, CONSTANTE_ARRAY3);
?>